### ISSUE TITLE
Terminal / session numbering should start from 1

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#115]
Logically I am used to having terminal tabs with numbers which start from 1. That way it is pretty natural to hit `<Super>+1` and switch to tab number 1.

With terminix, terminals (split panes) and sessions start with number 0, which means I have to reach out all the way to the right on my keyboard to switch to the first terminal - `<Super>+0`.

You could say that I could configure keyboard shortcutl `<Super>+1` to switch to terminal 0, the issue with that is tha the number of the terminal is visible.

**Comment by vaijab** [comment]
In fact, `<Super>+NUM` shortcuts do not work when used for either switching between terminals or sessions.

**Comment by gnunn1** [comment]
You make a good point about having to reach for the 0 key versus the others, I don't have any issue with re-numbering the sessions and terminals unless someone has a strong counter argument for it. I'll blame the programmer in me that thinks of 0 as first since lists and arrays in most languages are 0 based. With this change, 0 would move to be a synonym for 10. 

I can reproduce the issue with the <super> key, I'll have a look it.

**Comment by vaijab** [comment]
Cool. Sounds like a plan. 0 normally takes you to a terminal tab number 10 in other terminals.

Thanks.

**Comment by gnunn1** [comment]
Re-opening, forgot to renumber sessions.

**Comment by vaijab** [comment]
@gnunn1 thanks for fixing this. I just upgraded to 0.53.0 and I can see that in the shortcuts configuration, numbering is still wrong. For example `Switch To Session 0` shortcut actually switches to a session number 1. It's a minor issue, but can confuse a lot of people.

**Comment by gnunn1** [comment]
@vaijab Thanks, fixed for next release and updated localizations to say '10' instead of '0'
