### ISSUE TITLE
A way to make open sessions more visible

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#117]
You access running sessions from the sidebar, but it is very likely you forget you have some session open, since there are no tabs. 

One way is to add a badge counter on session button. So when you have 2 hidden session, it would display {3}. I'm not entirely sure this is the best way to fix the issue, but I think it would be a great helper for start.

**Comment by gnunn1** [comment]
I was thinking of replacing the icon with a counter using the same circular style used in the sidebar to indicate the session number. When you only have one session, icon is shown. As soon as more then one session is in play icon is replaced with counter. 

Keeping the icon and putting in an overlay is challenging due to the small size of the icon, I played around with this for notifications with limited success.

**Comment by alex285** [comment]
@gnunn1 Actually I was thinking the same, it will be an improvement over the current, but again I'm not entirely sure it would be a totally cool way. Too much numbering all over the place!

Is it possible at some point to come up with a smart way of in-app notifications? Like "Hey, you have 2 running sessions", but without being distracting? For example there is a message, "Something wrong with the session" in a dialog window, which is the definition of distracting :)

 In any case I would be totally happy with the numbering!

**Comment by gnunn1** [comment]
I think I may have gotten badges working after all due to my madz cairo skilz :)

Seriously, what do you think of this? The badge appears with the count when there is more then one session.

![screenshot from 2016-02-29 21-01-57](https://cloud.githubusercontent.com/assets/9358238/13417327/e2908c1c-df27-11e5-866a-21b28386d463.png)

**Comment by gnunn1** [comment]
Done

**Comment by alex285** [comment]
Awesome! Thank you!
