### ISSUE TITLE
An alternative way to open sessions thumbnails with mouse

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#119]
Is it possible to provide an alternative way of launching sessions workspaces with mouse? For example, with some press-down and push from left to right, or pressing sensitivity?

I'm not sure that can be done on VTE view, but if you had a small 5px width sidebar on the left? Would a left sidebar (experimental, optional?) decrease usability on the overall use of terminal? It works okay on code editors that have a similar use to Terminal. 

The issue here is that from use I dont find convenient the sessions button. I find my self always using the shortcut to open the sessions, although I'm mostly a mouse-guy.

**Comment by gnunn1** [comment]
I played around with using gestures to try to spit terminals but could never get it working right using a mouse to simulate it. The problem for me is I don't have a touch screen on anything so I can't really do any development that involve gestures, hopefully the project can attract some additional developers who could look at this.

The other option would be to increase the options in the context menu beyond just the Copy, Paste, Select All options that are there. I think this would be the most obvious choice, I'm not keen on adding new UI elements for this since there is a button for this function already.
