### ISSUE TITLE
Pass F10 to apps

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#129]
Pressing F10 focuses the "View session sidebar" button, instead of forwarding it to the application running inside the terminal (let's say Midnight Commander).

**Comment by phw** [comment]
There is an option for that: Uncheck "Enable the menu accelerator key (F10 by default)"

**Comment by egmontkob** [comment]
Sure, sorry for bothering you :)

**Comment by gnunn1** [comment]
It's never a bother, I really appreciate you looking at Terminix. Given your expertise with the VTE and apps that use it you know where all the problem areas are so please feel free to submit as many bug reports as you want. :)

I wonder though if I should be enabling this option by default. From what I understand, GTK uses this key to focus the menubar by default and since Terminix doesn't have one it might make sense to just enable it always. I'll look into this further.

**Comment by whitebyte** [comment]
Hi,
I also stumbled upon F10 issue while working with Midnight Commander over SSH. I'm using KDE and it seems that F10 is free by default, so I was a bit surprised with this binding.

**Comment by egmontkob** [comment]
I'd also vote for changing the default.
