### ISSUE TITLE
session sidebar always visible

### ISSUE THREAD

**Issue by francescomeloni** [gnunn1/terminix#132]
is it possibile to have session sidebar always visible?

**Comment by gnunn1** [comment]
It's an idea I've considered as well, unfortunately I have  significantdoubts about whether it is possible technically due to the way GTK is structured. It was challenging enough getting the sidebar to work as it is let alone make it visible all the time with real time updates.

The best way I can see making it work is replace the existing GtkNotebook that is used in Terminix with a custom container that enables the non-visible sessions to be drawn directly without resorting to offscreen windows. I have a feature request open with GTK (https://bugzilla.gnome.org/show_bug.cgi?id=761837) that if it gets traction I'll re-consider, but at this point I can't commit to doing this.

**Comment by seanf** [comment]
Coming from Konsole, the inability to see a list of the other sessions (which I suppose would be tabs in Konsole) without hitting a key or a button is disappointing. But for that, a live screenshot is overkill: just a name is often enough. 

What about an option for a permanently visible list of sessions, but without the screenshot preview? I guess I'm asking for a tab bar, although perhaps it could be presented in some other way.

**Comment by gnunn1** [comment]
@seanf While I can understand and sympathize with the request, as I said in #12 I'm not interested in maintaining two UI conventions as it's just too much effort.
