### ISSUE TITLE
Include a visual aid to synchronized input

### ISSUE THREAD

**Issue by xisberto** [gnunn1/terminix#134]
When using the sync input option, it may be dangerous to forget about it. Could it be possible to move the option to the title bar? Or even add "synchronized input" to the window title.

**Comment by gnunn1** [comment]
I've thought about this as well. What I'm thinking of doing is adding a toggle button to each terminals titlebar that appears when sync input is active, The button can be toggled on/off for each terminal, on by default, so that the user can decide exactly which terminals are participating in the shared input. It would also fill the role you are looking for, a visual indicator that sync input is on.

**Comment by xisberto** [comment]
Yes, this was a second thind I thought when writing the feature request: that some terminals could be excluded from the shared input.

Good to know that you have already an eye on this.
