### ISSUE TITLE
Open new instance as vsplit/hsplit/session/window

### ISSUE THREAD

**Issue by stevebarratt123** [gnunn1/terminix#165]
It would be super useful if terminix offered this functionality as a preference:

When I hit my global keyboard shortcut to run terminix, it opens a new instance, OR if one already exists, bring that window to foreground and split the current session pane vertically (or alternatively, create a new session, new window, or a vertical split; user configurable through preferences menu). 

(ps thanks for making this rad terminal emulator! its cool to move away from patched gnome-terminal at last)

**Comment by gnunn1** [comment]
I think the best way to handle it is through command line parameters rather then some sort of option. Terminix supports the concept of command line actions some of which let you split terminals from the command prompt but they do require to be run from within a terminix terminal. See the wiki here:

https://github.com/gnunn1/terminix/wiki/Command-Line-Actions

I could maybe look at letting this be used outside a terminal context by assuming whichever session/terminal as focus is the one that should be actioned against.

**Comment by stevebarratt123** [comment]
Yes, those functions are halfway there. The catch is that the action should give a single simple session if it is starting the process, but perform the split/etc action if a terminix instance exists already.

**Comment by gnunn1** [comment]
Actually, I think I'm mis-understanding. When running a new instance of terminix when one is already running, instead of opening a new window which is the default, you want this to be a preference with the following options:

* Open New Window
* Open New Session
* Split Terminal Horizontally
* Split Terminal Vertically

Let me know if I have it incorrect. On the plus side, I did modify things so you can execute actions outside of a terminix instance so something was still accompished :)
