### ISSUE TITLE
Split buttons in the popover menu

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#173]
I've had a go at adding the split buttons in to the popover menu but for some reason they get added in a disabled state:
![terminix](https://cloud.githubusercontent.com/assets/422013/13969498/319a3b96-f07b-11e5-9850-906ccfb7ca76.png)

The changed code can be seen in https://github.com/alexwhitman/terminix/commit/2b0b64798abad8cd57ba4df74c3ceddc95ca414b

Two questions:
1. Are you interested in the feature being added?
2. If yes, any ideas as to why the buttons aren't enabled?

**Comment by gnunn1** [comment]
1. I'm OK with it, beefing up the popup has been on my personal todo list

2. This is usually because it can't find the action for some reason, usually because the action name is not correct (i.e. using name instead of detailed name for example). I do set the enabled state of these two actions specifically in updateActions but they are only disabled if the terminal is maximized. I don't see an obvious problem with your code though.

**Comment by gnunn1** [comment]
I think I see the problem, the context menu uses bindModel which takes the prefix, thus the menu model is created there with actions with just the bare name. With your shared method for creating the split buttons you are using the detailed name which when used with the context menu is essentially doubling it up.

Best solution would likely be to use bindModel for both context menu and the menu button popover so it is consistent.

**Comment by alexwhitman** [comment]
Yep, that was it, thanks.  Pull request incoming.
