### ISSUE TITLE
Use Transifex

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#204]
Hello,
I think the best way to translate the application is using Transifex! this will allow the translators to see the untranslated strings, languages..
Btw, i can manage the transifex account if you want to , and create a new PR whenever a new language is translated.

**Comment by MingcongBai** [comment]
https://github.com/gnunn1/terminix/pull/203

> BTW, just as a random note... Can we move some of these work onto Transifex so it will be easier to notify translators (regarding changes in the translation), and for you to import them when time comes for a release (and make them do it quicker before it would be too late).

**Comment by phw** [comment]
I second that in general, this was also shortly discussed at https://github.com/gnunn1/terminix/pull/92

I actually looked into setting it up back when I did the translation extraction. One reason I stopped was because I do not find the integration between Transifex and Git that convincing. The way I know how to get a more or less decent synchronization is:

1. In your Transifex project import the source file pot file once
2. Set up Transifex to periodically pull an updated pot file directly form https://raw.githubusercontent.com/gnunn1/terminix/master/po/terminix.pot
3. To sync the Transifex translations with the local po files somebody needs to run the Transifex CLI, e.g. with a script like this: https://github.com/phw/peek/blob/master/sync-translations.sh

What you don't get with this workflow is a) automatic import of new translations into Git and b) Git commits that are attributed to the translator. Not sure how important those things are. Does anybody know how to do this in a better way?

I have recently used [Weblate](https://weblate.org/de/) in a project of mine, which really provides nice integration with Git. I also find the UI a bit more straightforward (but maybe not as nice) as Transifex'.

**Comment by gnunn1** [comment]
From my point, ideally I'd like the solution to inter-operate seamlessly with github in the sense of that it automatically pulls from github when the .pot file has changed pushes localization updates via pull requests back to github The less I have to fiddle with things the better.

I had a brief look at Transifex and it doesn't look like it has that capability, as @phw noted above someone, presumably me, would need to run the CLI tool to do the sync'ing. I'd have to see what's involved in getting this hooked into the workflow though that example script from Peek is a two liner so maybe it's relatively easy. 

Thanks @phw for the pointer to Weblate, I'll check it out as well.

**Comment by edubxb** [comment]
Travis can be used to automate things, like to add new literals to translate to the "translation service" finally chosen, through and API or something similar.

As Weblate is FLOSS, I prefer it :yum:

**Comment by gnunn1** [comment]
I've sent a request to Weblate for free hosting.

**Comment by gnunn1** [comment]
So Terminix is now on Weblate at the following URL:

https://hosted.weblate.org/projects/terminix/translations/

@phw I have added weblate to the repo to receive notifications of changes as well as added the weblate push user to allow pushes to automatically happen. Is there anything else you would recommend I do before I go live with this?

**Comment by frnogueira** [comment]
pt_BR 100% ;)
Congrats, @gnunn1 !

**Comment by gnunn1** [comment]
@frnnoguiera I don't think the automatic push back to github is configured yet though, I'm going to need to sync changes manually in the meantime.

**Comment by frnogueira** [comment]
Great!
I don't know about this process...

**Comment by gnunn1** [comment]
@frnogueira No worries, I should have mentioned to hold off but it's all good.

**Comment by gnunn1** [comment]
Just an FYI, I need to sort out a git conflict in weblate tonight, so please hold off updating translations until after that.

**Comment by edubxb** [comment]
I'm working in the Spanish translation.

**Comment by gnunn1** [comment]
@frnogueira There were some problems with the pt_BR file as it had numerous duplicates and wouldn't compile, I suspect something happened in the exchange between git repos. I cleaned it up, can you have a look and confirm it looks good.

**Comment by gnunn1** [comment]
Updated home page to reference Weblate for translations, closing this issue.

**Comment by frnogueira** [comment]
I'll looking for...
