### ISSUE TITLE
Loading from multiple sessions at once breaks the "child design"

### ISSUE THREAD

**Issue by nikolay-n** [gnunn1/terminix#206]
Hi all,

if I execute the following command:
`terminix -s Default.json -s Default.json`

the design is broken in the second session (see attachments)

First session is OK:
![firstok](https://cloud.githubusercontent.com/assets/3336734/14245717/6421626e-fa63-11e5-99f8-b109b71b50c6.png)
Second session is broken:
![secondbroken](https://cloud.githubusercontent.com/assets/3336734/14245749/9a0868dc-fa63-11e5-80b1-62b1867fa78d.png)

[Default.json.txt](https://github.com/gnunn1/terminix/files/202231/Default.json.txt)

**Comment by egmontkob** [comment]
I guess the same rule of thumb applies as in #161: For the duration of setting up the layout, "resize" should be disabled for child1 and enabled for child2 of every paned, otherwise Gtk+ messes it up when many paneds are nested.

**Comment by gnunn1** [comment]
@egmontkob Thanks for the thought but I'm not sure that's the issue here as I'd expect to see similar behavior for session 1 as 2. I wonder if it's related to whether session 2 has been mapped, realized and allocated by GTK since it is a page in a GTKNotebook that may not be visible yet, I may need to defer creating the session.

Anyway, I can reproduce it so I'll have a look at this in more detail tonite or tomorrow.
