### ISSUE TITLE
Terminix starts in root directory!!!

### ISSUE THREAD

**Issue by hongquan** [gnunn1/terminix#214]
When I launch Terminix, it starts in root directory, instead of my home directory. It is weird. Please fix.

![terminix default_054](https://cloud.githubusercontent.com/assets/314607/14340003/419754e6-fcad-11e5-9705-7eaae76a38e6.png)
It happens with Terminix 0.56.0, built from git source.

**Comment by gnunn1** [comment]
I can reproduce using the Unity launcher. For some background, Terminix used to automatically default to the users home directory if no directory was explicitly passed to it. However there are a number of bugs and behavior issues with that so now it defaults to the working directory that is set when it is run.

Based on my quick testing, it looks like Unity doesn't set the current working directory to the user home directory like Gnome Shell does which strikes me as a bit weird. Looks like if I drive everything off PWD instead of cwd it should work, when launched from Unity Shell the PWD environment variable is set to the users home directory.

**Comment by gnunn1** [comment]
Get the latest from git and rebuild, hopefully this commit will fix it for you like it does on my Ubuntu VM.
