### ISSUE TITLE
Terminix does not read .bash_profile

### ISSUE THREAD

**Issue by Tigro** [gnunn1/terminix#240]
I saw that Terminix during start read .bashrc, but does not read .bash_profile with redefined PATH variable. So ~/bin path not available.

**Comment by phw** [comment]
That's actually expected behavior, unless you configure Terminix to run as a login shell. You can set the option "Run command as a login shell" in Terminix' profile settings.

See http://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell for an explanation of the differences between a login shell and a non-login shell and how this affects the files being sourced.

**Comment by Tigro** [comment]
Ok. Not a problem. Closing.
