### ISSUE TITLE
Option to pin the session sidebar or show a tab bar

### ISSUE THREAD

**Issue by almson** [gnunn1/terminix#242]
I'm not a fan of having any kind of tab/session switcher be hidden. Makes me disoriented. I think a pin icon would work nicely.

**Comment by gnunn1** [comment]
The sidebar can't be permanently pinned open due to limitations with GTK, the only way it might be feasible is by writing a custom GTK container which is a pain to do in D and I have no plans to undertake it on a might work basis.

Similarly tabs have been asked for before and I have no plans to introduce those as well, I like the sidebar personally though I can understand it's not for everyone.
