### ISSUE TITLE
Feature: Command completion (when not focused) should have desktop notifications

### ISSUE THREAD

**Issue by mehcode** [gnunn1/terminix#247]
The idea is that if the session does not have focus and a command completes, a success or error desktop notification would pop-up (and be click-able to bring focus back to the terminal that passed / failed).

**Comment by gnunn1** [comment]
This is already mostly supported via the patched Fedora VTE widget, see the Notifications are of the FAQ towards the bottom:

https://github.com/gnunn1/terminix/wiki/FAQ

The notifications don't include success/error, I don't think that's likely to be very feasible since there isn't an easy way for terminix or vte to see the exit code of the process.
