### ISSUE TITLE
Change fg and/or bg color for unfocused terminals

### ISSUE THREAD

**Issue by edubxb** [gnunn1/terminix#263]
As Terminator and iTerm2 does, could be a nice feautre that Terminix changes the fg and/or bg color of the unfocused terminals.

Currently only title in the terminal header changes it color.

**Comment by gnunn1** [comment]
I fooled around a bit with this but my current implementation has many issues that would need to be addressed. If you are building from source, set the DIM_TERMINAL_NO_FOCUS to true in constants.d to try it out.

**Comment by edubxb** [comment]
I made the change you suggested, but only works with the Light theme.

**Comment by gnunn1** [comment]
Like I said it has issues :)

I'm not sure my current poc approach is the way to go either, I believe
Terminator does it by actually changing the font colors.

**Comment by edubxb** [comment]
Yeah, you said it!

The Terminator way to do this seems a good way ;)

I think that your guess is correct... http://bazaar.launchpad.net/~gnome-terminator/terminator/trunk/view/head:/terminatorlib/terminal.py#L1190

**Comment by egmontkob** [comment]
See https://bugs.launchpad.net/terminator/+bug/1518111
and https://bugzilla.gnome.org/show_bug.cgi?id=758368

**Comment by gnunn1** [comment]
Thanks @egmontkob that is very helpful, I think I've found a good way to do this. My original attempt used Cairo to draw an Alpha rectangle, after doing some research I saw that using a Cairo compositing operator would likely produce better results. I've put in a new implementation and it seems to work pretty well with both light and dark themes.

Since it is a post-processor at the draw level it avoids the issues with setting the VTE palette colors that you noted like dealing with colors set via escape codes, etc.

@edubxb If you have some time, can you give it another try and let me know what you think. One thing to note, like Terminator there will be a scaling factor from 0 to 1 which controls the alpha level. There is too much variance in color across dark and light to use a hard-coded value so depending on your theme you may need to adjust it. To do that, in terminal.d:1580 you will see this line:

```
cr.setSourceRgba(bg.red, bg.green, bg.blue, 0.2);
```

The scaling factor is 0.2, try setting different values and see if you can achieve a good result with the theme you are using. If you can, we are probably good to go in terms of making this available, I'l just need to add a preference and slider to the preferences dialog to control the factor.

**Comment by gnunn1** [comment]
I suppose I should mention that the scaling factor is a value from 0 to 1 where 0 is completely transparent and 1 is completely opaque. So .5 would be 50% alpha.

**Comment by edubxb** [comment]
Just compiled the master branch and changed the value to 0.5, but nothing happens, not sure if I'm doing something wrong...

**Comment by gnunn1** [comment]
If you did a checkout, did you remember to change that DIM_TERMINAL... in constants.d back to true?

**Comment by edubxb** [comment]
Now I'm sure that I did something wrong, thanks!

**Comment by edubxb** [comment]
Look's good, now the only missing thing is to add the slider to change the alpha value as you suggested.

**Comment by egmontkob** [comment]
Looks nice indeed!
It seems to me that it shifts colors towards white in inactive panes. I'm wondering if it'd be better to shift them towards black, or mid-gray, or the terminal's background color, or even have a config option to choose among these. Could be worth experimenting a bit...

**Comment by phw** [comment]
Is this setting something that will be part of a color scheme?

**Comment by gnunn1** [comment]
@phw @egmontkob Right now it uses the theme color for INSENSITIVE which for the VTE might be the same as the theme background. I tried it with the VTE background as well but it didn't seem to look as good.

I'm debating about allowing to set the color used with the profile color scheme and putting the factor slider there as well. This would allow people to really tune it well. The con of course is it would need to be tuned for each color scheme.

The option to dim the unfocused terminals would remain global. 

Does that make sense to you guys, I'm quite open to suggestions.

**Comment by gnunn1** [comment]
So I'm making progress on this, anyone have any thoughts on how to make this UI suck less?

![screenshot from 2016-04-25 20-11-42](https://cloud.githubusercontent.com/assets/9358238/14804592/167f064a-0b22-11e6-8d81-0da7f121af17.png)

**Comment by gnunn1** [comment]
I think I'm going to revert the UI and simply add an Advanced menu button with a popover that has the highlight, cursor and dim color options. The button would be positioned next to the Use theme colors... checkbox and tied to it for sensitivity.

This should look much less busy and tuck these lesser used options away.

**Comment by phw** [comment]
Yes, sounds cleaner to me, too

**Comment by gnunn1** [comment]
I've checked in an initial implementation of this, I definitely need to do more testing though before closing this issue, particularly around the color tab of the profile editor as I'm not sure it's completely solid at this point.

As a bonus, added support for setting the cursor and highlight color with a new Advanced button.

**Comment by gnunn1** [comment]
Here's the new dialog, much cleaner.

![screenshot from 2016-04-26 21-27-59](https://cloud.githubusercontent.com/assets/9358238/14840890/d414e87c-0bf5-11e6-9047-f8b2279e1d9e.png)

**Comment by gnunn1** [comment]
Included in today's release, closing.

**Comment by thefonso** [comment]
![Screenshot from 2022-08-20 14-51-41](https://user-images.githubusercontent.com/85636/185762125-a9361a76-0fca-49a9-9258-e84b84320fb1.png)
In the advanced pop-up the "Dim" option is now missing. Can we get this back? Would be neat to be able to change the entire background color of the unfocused split window.
