### ISSUE TITLE
Feature request: visible tabs

### ISSUE THREAD

**Issue by alcir** [gnunn1/terminix#268]
There is a way to have all the open tabs visible in the top bar?

**Comment by gnunn1** [comment]
No there is not and no plans to add it, sorry.

**Comment by alcir** [comment]
Thank you for your answer, but there is a reason for that? Do you think that it is not useful?

**Comment by gnunn1** [comment]
It's the latter, I tend to think it's not useful because the tab doesn't convey enough information about what it contains. When I used to use gnome-terminal, I was constantly clicking through tabs trying to find the right one. In Terminix with the ability to split terminals it gets even more complicated.

There was a long discussion about this way back in issue #12 , you can review that for more background.

**Comment by protist** [comment]
FWIW this is the major issue keeping me from switching from terminator to terminix. From my perspective, I think the *thumbnails* don't convey enough information. I'd much prefer tab/window titles. Further, in terminator, you can easily rename these by double-clicking on them.

**Comment by gnunn1** [comment]
I understand your view and I know the sidebar isn't for everyone but my opinion hasn't changed, sorry.

**Comment by protist** [comment]
Fair enough. I understand. Thank you for the reply.
