### ISSUE TITLE
Terminx Tabs/windows

### ISSUE THREAD

**Issue by vendforce** [gnunn1/terminix#269]
Terminx was great unitl now , YES the new dock looks lovely but Now instead of having mulitple split terminals THAT I CAN SEE and very easliy interact with, I spend my days clicking the view tabs button to see what terminals are open and its confusing and so annoying 

WtF ? the reason terminx was so popular was becuase you could split the terminal vertical/horizontal and resize the width and height of the opened tabs  AND VIEW ALL THE TABS ON ONE SCREEN 

Now its a game of fucking wack a mole with the tabs button to view/switch tabs .. how did you think this is a good idea , this completely ruins the good work flow terminix split screen brought about  

so how different now is gnome terminal to terminix ? a tab slideout dock ? yea you can keep it .I might as well just go back to gnome terminal at least my mouse button wont wear out

I'm sick of people ruining apps when the start making it all about gui and not about work flow 

these days DE/applictions paradigm is " Hide everything if you can see it , its bad design "  

People dont JUST use the DE/applications for the gui affects etc they use it to work on/with, EVERYONE IS DRUNK ON GUI  these days 

Thers' a saying When drink is in, sense is out. I think there needs to be a new one
When GUI is in, sense is out

I'm all for nice design and beautiful gui look and feel , But when it starts to get in the way for work flow its a FAIL !!! 

Why stop with hiding the tabs , why not hide all the buttons its will look becautiful and clean and nothing showing that will make it look so unsmooth forget about functionality who the fuck needs that

**Comment by gnunn1** [comment]
I'm really confused by this rant, I can't think of anything significant that has changed in Terminix in the last few months. Before the sidebar was introduced there was a drop-down menu attached to the button for switching between sessions so conceptually it's the same flow?

Then you start ranting about splitting terminals, nothing has changed here as well. You still split terminals using the buttons in the title drop-down, context menu or via shortcut so nothing has changed here as well. I'm not sure why you think you can't split terminals, here's a screenshot of the latest version from master.

![screenshot from 2016-04-20 07-17-59](https://cloud.githubusercontent.com/assets/9358238/14675834/128844d8-06c8-11e6-966e-c944c448321f.png)

So try calming down and explain what the issue is like a mature adult. Posting a screenshot of the problem would be very helpful, maybe there's a bug that's not allowing you to split terminals?

**Comment by vendforce** [comment]
![screenshot from 2016-04-20 14-22-07](https://cloud.githubusercontent.com/assets/15267883/14675958/55bbf1a6-0703-11e6-9e0d-c2a9347a3ca5.png)

**Comment by dsboger** [comment]
@vendforce There is an option in the settings to show/hide the terminal title bar.

![terminix_change_title_bar](https://cloud.githubusercontent.com/assets/2356842/14676413/b63624fe-06e3-11e6-8519-2060fa2ba261.png)

**Comment by gnunn1** [comment]
Mature means learning to deal with your frustration and not acting like a five year old in a candy store when there Mommy refuses to buy them a chocolate bar. I work on this on as a hobby, I get enough crap to deal with in my job that I'm not interested in putting up with it here.

You have the terminal titles hidden which is a new option in Preferences (off by default). As a result, you can split terminals by right clicking the terminal to get the context menu, see screenshot below. If you don't see this context menu then open a bug and I'm happy to have a look at it.

![screenshot from 2016-04-20 07-32-20](https://cloud.githubusercontent.com/assets/9358238/14676311/25768490-06ca-11e6-9ded-484f2f7b3c9e.png)

You can also split terminals via shortcuts but note the shortcuts recently changed to reflect the new names which were chosen to remove ambiguity. If you want to set them back to the old shortcuts go to the Preferences window and the Shortcuts tab.

![screenshot from 2016-04-20 07-32-44](https://cloud.githubusercontent.com/assets/9358238/14676313/299252a2-06ca-11e6-919d-8cf51a2bdd5a.png)

**Comment by vendforce** [comment]
Oh fuck off you dickhead ,I didnt insult you till now ,
