### ISSUE TITLE
Global dim preference

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#290]
Sorry, it's a 2-in-1 bugreport :)

First, I got confused because altering the Unfocused Dim settings under Profile Prefs didn't make any difference... until I recalled there was a global pref to enable dimming. Just above the Dim profile pref there's the Transparency which doesn't have a global counterpart. So I'm wondering if maybe Dim shouldn't have one either. If someone wishes not to dim, they can disable it for each profile...

Second, Terminator dims all the panes if the window loses focus, Terminix does not, hence with multiple windows there's one non-dimmed pane in each, so the shade alone doesn't uniquely identify the focused one. Not sure which behavior makes more sense, I probably tend to vote for Terminator's.

So maybe the current global Dim option could be replaced by a different one choosing between the two kinds of behaviors... or a tri-state...

**Comment by egmontkob** [comment]
(Note the infamous focus bug that got fixed in Gtk 3.18.9: https://bugzilla.gnome.org/show_bug.cgi?id=677329)

**Comment by gnunn1** [comment]
Let me start by saying that I fully agree that the option isn't very intuitive.

The intent of the global option is to turn it on or off, the intent of the profile options is to tweak it's appearance. The appearance tweak options have to be in the profile since all of the other colors are there as well. The checkbox in the profile is to indicate whether to use the system color or a customized color.

In terms of eliminating the global option, I think you are suggesting that if the slider is set to 0 it effectively means no dimming just like the transparency scale? I'm with that, I'd just need to adjust the preference so it is off by default. The one downside is that people would need to adjust the dim across every profile if they want it to be globally enabled.

As to the last point, dimming all panes when the window loses focus, I'm OK with that too and it should be relatively easy to add.

**Comment by egmontkob** [comment]
> I think you are suggesting that if the slider is set to 0 it effectively means no dimming just like the transparency scale?

That's what I'm thinking about... It might be more logical, although perhaps less user-friendly, who knows. Or maybe if dimming is globally off then disable the per-profile slider and color chooser?

Just throwing in random ideas, the final choice is yours :)
