### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#298]
One of the often criticized change in vte-0.38/g-t-3.14 was the removal of background image support. All other vte-based apps followed and had to remove this feature.

However, you know the Gtk+ trick to paint behind a translucent vte, so you could bring it back.

A single background image stretching behind all adjacent panes could probably look awesome, although it's nontrivial to figure out how it should behave (e.g. what if the background image is a profile preference, and multiple panes have multiple profiles?)

(As much as some people love this feature, I myself would never use it, so I'm just throwing in the idea and let you figure out if/how to implement :) )

**Comment by gnunn1** [comment]
Like you I would never use this feature myself so it's not a high priority for me. I'll leave this open though as a means to judge how important it is to others though.

**Comment by gnunn1** [comment]
This is a note to my future self. After thinking about it, I'm not how feasible this is. The stuff I'm doing with dim is a post-process that occurs after VTE has drawn it's content. For an image background, I'd have to draw the image first and then have VTE draw on top of it. 

The only way I can think this might work is draw the image first and have the VTE background color be completely transparent. The other option I thought about was drawing the image on the underlying window, however given that the VTE doesn't show the window background when I was drawing a solid color as part of #303 I'm not sure the image would even appear.

**Comment by egmontkob** [comment]
> The only way I can think this might work is draw the image first and have the VTE background color be completely transparent.

Yup this should be the concept.

**Comment by gnunn1** [comment]
Here's my first attempt at this, one thing to note to make this work I'm back to adding CSS classes to individual items (i.e. terminal title bar, search bar, etc) otherwise they show transparent as well.

![screenshot from 2016-05-21 22-18-41](https://cloud.githubusercontent.com/assets/9358238/15451747/2ebb405e-1fa2-11e6-90c0-af6e2b4f315f.png)

**Comment by gnunn1** [comment]
So a couple of thoughts on this as follows:

* Need to alter the side bar code so when it draws the thumbnail the image is taken into account, right now the thumbnails are drawn solid since drawing them with alpha previously resulted in odd looking results.
* The image option would be global to the application and would not be per profile based
* Probably need to add the usual options for background images (scaled, tiled, centered) for determining how to fit the image

**Comment by egmontkob** [comment]
Hey,

Just wondering, wouldn't it be cool to mention this feature on the front page? :)

cheers!
