### ISSUE TITLE
Search bar is transparent with Ambiance

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#303]
Pretty much like #146, this time the Search bar is transparent.

(Please see the comments over there, I still reckon that an ultimate fix is possible, and might be worth it, rather than one-offs for each widget.)

**Comment by gnunn1** [comment]
I agree with you about the one-offs, however a problem I have is that as soon as I start drawing the window background any widgets besides VTE that you want to be transparent start picking up that color, in this case the scrollbar. Looking at that Ubuntu patch it's not obvious how it's getting the scrollbar transparency to work, I'll do some more digging.

**Comment by egmontkob** [comment]
Thanks for your work on this (as well as all others, of course)!

I'm really not experienced with Gtk+ so unfortunately I cannot help with the details, apart from pointing you to that patch.

**Comment by gnunn1** [comment]
No worries, a lot of time the comments I post are more for me, since I'm juggling this with my day job I need the reminders :)

**Comment by gnunn1** [comment]
So I got this all working... on GTK 3.20 only :(

Here's how popovers look in GTK 3.18 and early

![screenshot from 2016-05-06 14-37-38](https://cloud.githubusercontent.com/assets/9358238/15082940/8a6920f8-1398-11e6-92d7-d69abeecd9ae.png)

**Comment by egmontkob** [comment]
Not sure I'm following you... or did the fix for the search bar break the popover?

The popover works fine for me (gtk 3.18). It's the search bar (Ctrl+Shift+F) that's transparent (I should've attached a screenshot).

**Comment by gnunn1** [comment]
Sorry, I mean as you soon as you add the Window onDraw to draw the background instead of adding a CSS class everywhere the popover starts getting drawn as shown as above with that extra frame around it. I actually ran into this when I first started Terminix and then completely forgot about this issue when I abandoned painting the background manually in onDraw. Now that you've prompted me to re-visit it I'm running into it again.

It was interesting to try this again though because it works perfectly now in 3.20. Also, I fixed a few other related issues so even if I can't get painting the background to work as an alternative to CSS classes it was still a good exercise.

**Comment by egmontkob** [comment]
Oh, I see. Thanks for experimenting with it, and also it's great to have your findings documented :)

**Comment by gnunn1** [comment]
@egmontkob So I've checked in a change that simplifies this quite a bit and on the whole it seems to be working better, even though the methodology is a bit counter-intuitive. Instead of painting the window background, which causes the popover painting issue in 3.18, I simply added a CSS class to the session (i.e. page in GTKNotebook) to add a background coor equal to theme_bg_color.

Now the unintuitive part, is that I paint the background of the terminal (vte + scrollbar) completely transparent if there is a scrollbar CSS file for the current theme, otherwise no custom painting happens. This allows the scrollbar to be transparent and color match the terminal when supported. If no scrollbar CSS is detected then no transparent painting happens and the scrollbar inherits the background from the session CSS.

This whole concept is based on what I noticed when I was drawing the window background, essentially even though the window had a color drawn on it, as long as the VTE was transparent it was ignored by the GTK drawing code. 

Since only the terminal portion is painted transparent, the GTKPaned splitter handle is never affected I don't need to style it with a background color any longer.
