### ISSUE TITLE
Strings before app.run() not translated

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#311]
I just noticed that every localized string that is passed to `_()` before `terminixApp.run(args)` is called (but after textdomain has been set of course) does not get translated. This affects the descriptions of the command line arguments.

I could workaround this issue by calling `Main.init(args);` in app.d early. But I don't know enough about the Gtk lifecycle to tell whether this workaround is a proper fix. As GApplication is used here `Gtk.init()` usually is not required and I don't know whether it has some unintended side effects to call it twice.

**Comment by gnunn1** [comment]
Looking at the documentation [here](https://wiki.gnome.org/HowDoI/GtkApplication/CommandLine)

> GApplication supports parsing of additional commandline options if they are specified using g_application_add_main_option_entries(). The ideal place to call this is from the _init() function of your application or (if not subclassing), after g_application_new() has returned.

Right now I think I'm adhering to that since it happens after the super() call in the constructor. Based on your description of the issue and the requirement for Main.init though I'm not sure there is a good pace to hook it in.

Looking at the docs for glib [Internalization](https://developer.gnome.org/glib/stable/glib-I18N.html) I wonder if the proper solution is to call bindtextdomain, that textdomain call is essentially a terminix call, it doesn't actually call out to glib. I'll have a look at the source for a comparable program like gedit and see what they do.

Can you confirm that the command line for gedit and gnome-terminal are localized on your system?

**Comment by phw** [comment]
> Looking at the docs for glib Internalization I wonder if the proper solution is to call bindtextdomain, that textdomain call is essentially a terminix call, it doesn't actually call out to glib. I'll have a look at the source for a comparable program like gedit and see what they do.

From my own limited experience the whole four lines in the example given in that documentation are needed for proper localization support in Gtk:

```
setlocale (LC_ALL, "");
bindtextdomain (GETTEXT_PACKAGE, DATADIR "/locale");
bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
textdomain (GETTEXT_PACKAGE);
```

At least bindtextdomain should be called, and it should happen before initializing Gtk. But as far as I could see the D bindings did not support this, is this correct?

And yes, gnome-terminal is properly localized descriptions in `gnome-terminal --help`.

**Comment by gnunn1** [comment]
Looked at the gedit source code, they are overriding init and adding the main options there.

**Comment by gnunn1** [comment]
@phw, I actually I think that workaround should be fine except I wouldn't pass any arguments to it. The documentation for gtk_application_new says it's OK to call gtk_init early if you need to:

https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-new
