### ISSUE TITLE
Terminal shortcuts don't work

### ISSUE THREAD

**Issue by Cybso** [gnunn1/terminix#342]
Some shortcuts don't work for me, even if I map them to other keys.

Shortcuts that DO NOT work:

- Maximize (splitted) terminal (works with button)
- Zoom/unzoom
- Split console (works with menu button)
- Copy/Cut/Paste (works with context menu buttons)
- shortcut overview (Edit: see below)
- and some others...

Shortcuts that DO work:

- Show sidebar
- Change splitted console sizes
- Switch to terminal X
- Switch to session X
- and some others...

It seems to be a problem with the actions itself, because when I remap working shortcuts to the keys of non-working shortcuts they still work (for example, when I map "view sidebar" to "ctrl++" this shortcut now opens the sidebar. On the other side, if I map "Zoom in" to the F12 key, it doesn't zoom. Instead it prints "~" characters into the terminal.

I'm using Linux Mint Debian Edition 2.0 (basically Debian 8 with some additional packages). I've tested it under Cinnamon and KDE, with version 1.0 and current github trunk.

**Comment by Cybso** [comment]
On further investigation I found out that (beside ACTION_SHORTCUTS, which is disabled through the 

`if (Version.checkVersion(3, 19, 0).length == 0) {`

condition, all shortcuts defined in terminal.d are ignored.

I have no experiences with D (or GTK3), so do you have any hints for me how to trace down this problem?

**Comment by gnunn1** [comment]
I'm not sure what the issue is, I just tested copy/paste on my local machine and it works as expected. Obviously for the terminal shortcuts to work the terminal itself must have focus, and some of the actions do depend on state (i.e. copy only works if something is selected, paste if something is in the clipboard, etc). Also, I'm assuming you don't have the Read Only switch enabled in the terminal.

The actions are created in the createActions method in terminal.d, you could try putting a trace statement before the insertActionGroup line to make sure the actions are being added correctly.

Also, I don't do any testing on KDE or Cinnamon but it shouldn't make a difference for this since it is a GTK 3 feature. Having said that, if you have Gnome Shell installed might be worth trying that as well just to be sure.

**Comment by Cybso** [comment]
I've already traced that, the actions are inserted but don't get executed. Also, "Synchronizing Input" works, so the key events seems to reach the EventBox.

At the moment I assume it might be a bug in Debian's version 3.14.5 of libgtk-3. I'll set up a VM with Debian Testing (comes with 3.20) to verify this.

**Comment by gnunn1** [comment]
I didn't realize that you were using GTK 3.14, I can confirm in Oracle Linux 7.2 which I have running in a VM. I'll have a look at this.

**Comment by gnunn1** [comment]
I had a look at this tonite but I don't see any obvious reasons why this isn't working. It's not just the fact that I'm using insertActionGroup as the session actions also use that.

I'll have to do some more investigating.

**Comment by Cybso** [comment]
I think this could be related to the following changelog entry in GTK 3.15.3:

> * GtkWindow now starts from the focused widget when looking for actions that are activated by accelerators 

See git diff at:
https://git.gnome.org/browse/gtk+/commit/?id=235837ad4932e60f46db97934be1dfb5200e185e

And bug report at:
https://bugzilla.gnome.org/show_bug.cgi?id=740682

Sadly the bugreport contains no hint how to work around this problem. Might it be possible to intercept the events in the session and delegate them manually into the active terminal?

**Comment by Cybso** [comment]
Is it possible to start a second process, even if another instance is already running? At the moment I cannot use terminix to edit terminix' code because when I try to start the freshly compiled binary it would open a new window within the the running process instead.

**Comment by gnunn1** [comment]
Not that I'm aware of, I usually just use gnome-terminal when working on terminix.

As to your other question, yes it should be possible to intercept the keystrokes and figure out the keystrokes by iterating over the settings. If you want to tackle this I can give you some guidance, otherwise I'll look into it this weekend.

**Comment by gnunn1** [comment]
Actually, it looks like you wouldn't even have to walk the settings since GtkApplication has a method to return the action name associated with an accelerator, getActionsForAccel. So basically call that for the accelerator, if the action name starts with "terminal." then lookup the action in sagTerminalActions and invoke it.

Of course everything needs to be wrapped in a GTK Version check.

**Comment by Cybso** [comment]
Here we go... works fine for me!

[terminix-fix-for-issue-342-v1.patch.txt](https://github.com/gnunn1/terminix/files/282932/terminix-fix-for-issue-342-v1.patch.txt)

**Comment by gnunn1** [comment]
Thanks!

**Comment by Cybso** [comment]
No problem :-) This is a great terminal, it already replaced Konsole as my primary terminal emulator within two days!

I've just realized that I've pasted a comment line from createSessionActions. The first line should read:

>  * Create actions that will be delegated to the active terminal.

**Comment by gnunn1** [comment]
I haven't tried this, but just wondering If you tested changing an accelerator in the preferences dialog to make sure there is no impact.

**Comment by Cybso** [comment]
Yes, I've tested that on the first run, no problem.
