### ISSUE TITLE
no plattform information in the releases

### ISSUE THREAD

**Issue by buhtz** [gnunn1/terminix#36]
In your releases are no informations about the plattform they support. You should explicte tell the user that it is a 64bit binary.

**Comment by gnunn1** [comment]
I've pushed a changed to README.md that is explicit about there being no 32 bit version available and I'll add a FAQ entry about this as well. I'm not planning on explicitly saying this on each and every release since I've no intention to support 32 bit, though if someone wanted to compile it and fix issues for 32 bit I'd be happy to accept PRs for it. I just don't have the bandwidth for it considering how little used 32 bit is these days.
