### ISSUE TITLE
[Feature request] Change title from command line

### ISSUE THREAD

**Issue by simonbcn** [gnunn1/terminix#395]
Actually if I want to assign a custom title (_determined in execution time_) to Terminix session, I can't from command line.

**Comment by gnunn1** [comment]
I think I know what you mean bu just to be clear, the title would go to the terminal and not the session and hence the title appears in the terminal titlebar and not the headerbar.

This should be easy to add, it's just adding a new command line switch so within a terminix terminal you could do something like:

```
terminix --title "My new terminal title"
```

**Comment by gnunn1** [comment]
Done, as discussed this only works when executed within a terminix terminal, using this option outside of terminix does nothing

**Comment by simonbcn** [comment]
Thanks, but this isn't useful. If I open Terminix from a script (_this is the case_), how can I change the title?

**Comment by gnunn1** [comment]
The problem as I see it is that there are two use cases:

- Set the custom title of the current terminal
- Launch a new terminal with a custom title

The issue is I don't see an easy way to distinguish between the two. For example, if you type ```terminix --title MyTitle``` within terminix is that to launch a new instance with the custom title or change the current terminal?

I fooled around with something like this to satisfy your use case:

terminix -x "terminix -t UpdateSystem; yaourt -Syua"

It doesn't work though, looks like the execute parameter doesn't work with chained parameters. If I fix that issue, would this technique address your concern? 

Also, it would be relatively helpful if you could describe what you are doing in more detail. Is your script just launching terminix to the command prompt or is it actually executing a command? If you could paste the line in the script that launches terminix that would allow me to test your extra scenario.

**Comment by simonbcn** [comment]
In my case I open a new terminal with a FTP session when I press a key. The title is the version of lftp program: `title="lftp-v$(lftp --version | head -n1 | awk '{print $4}')"`

I think the two use cases, you mentioned, are irrelevant here because there is a parameter in the preferences that controls this:
![seleccion_002](https://cloud.githubusercontent.com/assets/428231/16839133/b105a0fe-49cd-11e6-977a-cf3734e9114a.png)

**Comment by gnunn1** [comment]
Unfortunately the two use cases are not irrelevant as far as I can tell, a user can have the On new instance set to "New Window" and still want to be able to both change the title for the current terminal and when launching a new one.

If you make a second script that actually does the FTP you could set the title in that successfully. This works fine for me as an example, I have a script called update.sh which runs yaourt to update my system:

```
terminix --title "Update"
yaourt -Syua
```

And I can then execute it as ```terminix -x update.sh``` and my terminal title changes to ```Update``` before executing yaourt. So in your case, a script something like the following pseudo-code:

```
title="lftp-v$(lftp --version | head -n1 | awk '{print $4}')"
terminix -t "${title}"
lftp ....
```

BTW, how are you doing this on your current terminal?

**Comment by simonbcn** [comment]
If I execute `terminix` in a open terminix, it opens a new instance. But if I execute `terminix -t test` it only changes the title the actual instance. 
If I execute `terminix` in a open terminal (_not Terminix_) or from a script, it opens a new instance. But if I execute `terminix -t test` it does the same and it ignores the `-t` option.
For me this makes no sense. Same command does different things?
`terminix` should open always a new instance. And `terminix -t test` a new instance with custom title. So simple.
The change of the title of actual instance should be done by running terminal application (_bash/zsh/screen/..._).

**Comment by gnunn1** [comment]
Alright, you've convinced me. I'll flip it around so title acts like an override similar to the profile command line switch,

**Comment by gnunn1** [comment]
Changed made, try it now.

**Comment by simonbcn** [comment]
it works. Thanks.

**Comment by Littlejd1997** [comment]
Hate to revive an old thread but I just ran across this. I am looking to use an activity watcher (ActivityWatch, similar to Timing on OS X), and I would like to dynamically set the tilix window title dynamically, so the watcher can read the title and know "what I'm doing". Could this feature be added as an `Action` or something?

**Comment by john9631** [comment]
I have solved the problem (after installing urxvt and solving it that way).

It won't work with wayland (until they pull their heads out on security) but it will work with xorg.  You just need to use xbindkeys.  To change the name to Vim say you do this:

`xdotool set_window --name "Vim" $(xdotool getactivewindow)`

I actually wanted it so that when I was using Vim, the editor could change the window name as you moved around buffers.  So, for any vimmers, this was the addition to my .vimrc:

`au BufNewFile,BufRead *.*  :silent exec '!xdotool set_window --name "vi %:t" $(xdotool getactivewindow)'
au BufEnter *.* :silent exec '!xdotool set_window --name "vi %:t" $(xdotool getactivewindow)'
au VimLeave *.* :silent exec '!xdotool set_window --name "Vim" $(xdotool getactivewindow)'`

Enjoy your dymically renaming Tilix window 🙂

**Comment by john9631** [comment]
For Vim I noticed that Tilix would change the title when I move to a different pane & wouldn't correct on return until one of the autocmds was triggered.  I added one based on mouse moves and removed two of the others so my vimrc now includes:

```
au BufEnter,CursorMoved *.* :silent exec '!xdotool set_window --name "vi %:t" $(xdotool getactivewindow)'
au VimLeave *.* :silent exec '!xdotool set_window --name "Vim" $(xdotool getactivewindow)'
```
