### ISSUE TITLE
Keyboard controls enchantments in session sidebar

### ISSUE THREAD

**Issue by Redwan13** [gnunn1/terminix#422]
When user opens session sidebar, he can use arror keys to navigate through sessions. This behaviour lacks cycling (going from last session to first with down-arrow) and navigating through sessions via number keys.

**Comment by gnunn1** [comment]
I added support for selecting a session via a number key when the sidebar is open. I looked at doing the cycling but couldn't get it to work properly in the sense the initial cycling works but navigation after that becomes wonky. I tried a variety of things including using the keynav-failed signal, key-press and key-release with no luck. 

If you know of an open-source GTK application that does this cycling I would be glad to have a look at what technique they are using otherwise I'm to close this issue.

**Comment by Redwan13** [comment]
Sadly, I don't know any.

**Comment by jurgenhaas** [comment]
I'm coming over from #1180 and I'm struggeling to get the issue. Scrolling down is cycling OK, just scrolling up isn't.
