### ISSUE TITLE
Click on scroll button of the mouse on window issue

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#437]
The click on scroll button of the mouse on window heading should send the window behind the other windows. This is expected on Ubuntu. Please, fix that.

**Comment by gnunn1** [comment]
Terminix uses CSDs, if you want this middle click to work you need to disable the CSD so that Terminix uses a normal system titlebar likes the other apps.

This option is not visible in Terminix, but can be enabled in dconf-editor as per the screenshot below which shows the disable-csd option in bold:

![screenshot from 2016-08-13 22-22-42](https://cloud.githubusercontent.com/assets/9358238/17646738/944f5c5e-61a4-11e6-9d65-9e5a5f6282e5.png)
