### ISSUE TITLE
Feature request: confirmation before paste

### ISSUE THREAD

**Issue by Asher256** [gnunn1/terminix#442]
Hi,

This feature is interesting for people who copy/paste commands as root. It can avoid many mistakes (sometimes, the wrong data can be in the clipboard, even though you pressed CTRL-C).

Example:
- The Terminix user presses CTRL-V
- Terminix asks: "Are you sure you want to paste: rm -fr /"
- The user can choose yes / no

Thank you in advance!

Asher256

**Comment by egmontkob** [comment]
Just FYI: https://bugzilla.gnome.org/show_bug.cgi?id=697571

**Comment by Asher256** [comment]
+ egmontkob

Another reason why a confirmation is necessary for Linux administrators.

**Comment by gnunn1** [comment]
I'm thinking of combining this with the unsafe paste dialog and making it a tri-state option as follows:

* Never Prompt
* Prompt When Unsafe Paste Detected
* Always prompt

The default would be the second one. Might also be an opportunity to introduce some of the capabilities from iterm2 advanced paste:

https://www.iterm2.com/features.html

**Comment by Asher256** [comment]
+1 gnunn1
I like the idea.

**Comment by gnunn1** [comment]
Here's what I have so far, I need to spend some time reviewing @egmontkob's link to understand the escape options that iterm2 has.

![screenshot from 2016-09-15 16-03-06](https://cloud.githubusercontent.com/assets/9358238/18565548/255c45cc-7b5e-11e6-8fdf-0bb522f7e3aa.png)

This is implemented as a different shortcut, I opted against doing the tri-state thing because I can see lot's of situations where a user wants the dialog off by default but occasionally pops it up to modify what's in the clipboard before pasting.

**Comment by gnunn1** [comment]
I added the option to remove control codes (i.e. codes in the 0-31 ASCII range except tab, lf, ff and cr).

**Comment by egmontkob** [comment]
Oops, I forgot to link: https://bugzilla.gnome.org/show_bug.cgi?id=753197. No need to add such an option, vte removes them anyway.

**Comment by gnunn1** [comment]
@egmontkob Thanks for the info, I'll remove it.

**Comment by gnunn1** [comment]
Commit reverted, I'm going to close this as I'm not sure how useful some of the other iterm2 transform options really are. Folks can open new issues as required.
