### ISSUE TITLE
Command not executed when switching profiles

### ISSUE THREAD

**Issue by LionelR** [gnunn1/terminix#463]
If a profile is set with a personalised command, the command is not called when inside a session we want to switch to this profile. All others parameters (colors, background, ...) are set, but not the command.

**Comment by gnunn1** [comment]
Are you referring to switching to a profile when Terminix is already running and expecting that profiles command to run, or loading a session from a file where one of the terminals as a profile with a custom command to it and is not executing?

If the former, that's by design and isn't going to change. The reason being is to make it work whatever is running in the terminal (shell, other command, etc) would need to be killed and it's too easy to accidentallty switch and lose something important. No other terminal that I'm aware of does this, gnome-terminal for example won't run the command either when switching profiles on the fly.

If it's the latter, then that's a bug and I'd be happy to look into it.

**Comment by LionelR** [comment]
No, it's the former.
So, how do you tell Terminix to open a new session with the desired profile?

**Comment by gnunn1** [comment]
Command line parameters, use the -p or --profile switch. See ```terminix --help``` for more information.

**Comment by LionelR** [comment]
In Terminal, you have the possibility to go to File>Open a Terminal, and to choose the desired profile to use, without using the command line parameter

**Comment by gnunn1** [comment]
Try this in terminix, Go to preferences and choose the option "Prompt on new session". It's the first option on the first tab. Now when you open a new session it will prompt you to enter a name and choose a profile.

**Comment by LionelR** [comment]
Perfect!
