### ISSUE TITLE
Add option to start the app minimized

### ISSUE THREAD

**Issue by PombaM** [gnunn1/terminix#474]
**Motivation** :
I have set terminix to autostart on boot but since it lacks option to start minimized, it starts in the foreground, which is annoying :smile_cat: 

**Solution** :
Option to start this wonderful piece of software minimized, like the `--maximize` maybe a `--minimize` option

**Further info**:
Ubuntu 16.04.1 LTS (amd64)

**Comment by gnunn1** [comment]
So just to be clear, if I were to support this it would simply iconify (i.e. minimize) the application. It would not be running in the system tray. I'm asking because Gnome Shell doesn't really support minimizing effectively and I'm not sure about Unity, just want to make sure expectations are correct.

**Comment by PombaM** [comment]
That is would be lovely! Thanks.
