### ISSUE TITLE
Segfault when closing last session in sidebar

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#502]
From some discussion in #497 it looked like when the "Close window when last session is closed" is unset (i.e. always keep at least one session), it didn't work when closing the last session from the sidebar.

I've done some debugging on this and closing the last terminal in a session and closing the last session from the sidebar do both end up in `removeSession` in `appwindow.d`.  The reason the application still exits is because a segmentation fault occurs.  I'm not sure yet why it happens.

**Comment by gnunn1** [comment]
Thanks, I'll have a look tonight.

**Comment by gnunn1** [comment]
OK this should be fixed now, problem is some of the code in appwindow.d doesn't check that there is a session since without this option there was always at least one. Added a couple of null checks and it seems to work fine.

BTW, if you are not using gdb works really well for D code code and is great for finding these things. Just go ```gdb ./terminix``` and type ```run``` in the gdb console and terminix will start up. At the point reproduce the segfault and type ```bt``` in the gdb console to see the backtrace, it gives you line numbers and everything.

I learned just enough gdb to do that. :)
