### ISSUE TITLE
Question regarding width of terminix in quake mode

### ISSUE THREAD

**Issue by marksev1** [gnunn1/terminix#524]
Hello,

awesome terminal app, thanks for it!

Is it possible to change the width in the quake mode, I wouldn't like it to be covering the whole width of the screen.

Thanks!

**Comment by repsac-by** [comment]
At the moment only in X11, but not in wayland

**Comment by marksev1** [comment]
I'm ok with that, but how do i do it?

**Comment by gnunn1** [comment]
Just to elaborate, changing the width in Wayland isn't possible because once the width isn't 100% it refuses to allow the window to be positioned at the top of the screen.

If you absolutely want to change the width, login using an x11 session. You can do that by clicking the gear icon on the login screen where you enter your password and select 'Gnome on X11'.

**Comment by marksev1** [comment]
I am running X11, I am not running Wayland. So how do i do it via the user interface what do i need to press? :)

**Comment by gnunn1** [comment]
It's in the Preferences dialog (which is accessed via the Gnome app menu) under the Quake tab.

**Comment by marksev1** [comment]
Ah I see, very nice :). Thanks!
