### ISSUE TITLE
Configuration issue detected, even after fix

### ISSUE THREAD

**Issue by protist** [gnunn1/terminix#533]
I got the "Configuration issue detected" popup, then followed the [instructions](https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue), adding the following lines to the end of `~/.zshrc`.
```
if [[ $TERMINIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi
```
I then restarted, but still saw the same popup. I tested more:

* I made sure `/etc/profile.d/vte.sh` was being sourced, by editing in a logging step, which showed it was running fine.
* I tested removing the lines from `~/.zshrc`, and oddly enough, `/etc/profile.d/vte.sh` was still sourced.
* In terminix, I tested changing directory then splitting the window. With or without the lines in `~/.zshrc`, the new window correctly opened in the new directory.

I'm using an up-to-date Arch Linux system.
* zsh 5.2
* terminix 1.3.0
* vte3 0.46.0+5+g398a3f8

**Comment by gnunn1** [comment]
So I tried your block above and it is working fine for me in master on Arch, however I'm using vte 0.44 since I have vte3-notifications installed rather then the basic vte. That's the only difference I see other then I'm on master.

You could try downgrading to vte 0.44 and using the terminix-git package instead of terminix to see if either makes a difference.

**Comment by protist** [comment]
To be honest, I'm not planning on using Terminix because of issue #268. However, I did briefly try to troubleshoot for you anyway. Unfortunately I can't install `terminix-git` because the dependency `gtkd` fails to build for me. Sorry! I'll just close this issue then, since you can't replicate. Cheers.
