### ISSUE TITLE
In Quake mode, It's always on top. 

### ISSUE THREAD

**Issue by mifas** [gnunn1/terminix#536]
Is there any way to make this as optional ?

**Comment by phw** [comment]
Isn't that kind of the idea of quake mode, having a window that overlays the rest which I can quickly show with a keystroke?

**Comment by mifas** [comment]
Of course, But it would be nice, If we have that as optional. Tilda and Guake has this functionally.

**Comment by DebianUser2003** [comment]
I'd like to have this option, too. When in quake mode and you switch to another window (Alt-Tab or in Overview), now you get back to the quake window. Optionally hide it, when it loses focus.

**Comment by gnunn1** [comment]
I played with this, unfortunately there appears to be a number of problems with it. The first is if you select an application that occupies the whole screen and covers the quake window, there is no way to get it back in gnome-shell. This is because gnome-shell doesn't display the quake window in it's overlay since it isn't decorated and doesn't have a titlebar. To gett he window back, you have to press the quake key twice, once to hide it and once to bring it back again.

**Comment by danielkza** [comment]
@gnunn1 It seems there was some mistake, since right now it seems Terminix *does not* stay on top anymore at all. I bisected the issue to commit 6db4adc14d3c1dc04054c01be2f40779309c410a.

**Comment by gnunn1** [comment]
@danielkza Thanks for catching that, I made a mistake when I tried to just comment the option out instead of reverting it completely. Should be fixed now.

**Comment by danielkza** [comment]
@gnunn1 Working fine now, thanks!
