### ISSUE TITLE
Preferences window crashes Terminix

### ISSUE THREAD

**Issue by loops** [gnunn1/terminix#545]
Had to revert recent change to stop Terminix from crashing when attempting to open the preferences window.

Revert "Fix #541"

This reverts commit 79cfcc6dfbee681d00610b9e2eaf77d0bfe55527.

The backtrace is huge, but the error starts out with:

 *** Error in `/home/sean/devel/connect/terminix/terminix': corrupted double-linked list: 0x000000000
4cb9100 ***

**Comment by gnunn1** [comment]
I don't get the same issue, but I've noticed some other issues related to having multiple draw handlers in GtkD. For now, I've disabled the badge draw handler so it only kicks in if the VTE patch is in place, since I'm the only one using that patch this should resolve it as a temporary measure.

I'll bug the GtkD maintainer for thoughts on how best to handle this.
