### ISSUE TITLE
Quit bash shell without saving bash history

### ISSUE THREAD

**Issue by igor-dyatlov** [gnunn1/terminix#547]
Disabling HISTFILE leads to the fact that as long as you do not leave the current session, any commands that you will perform will not be saved in a file bash_history history: `unset HISTFILE`

It would be useful to have a checkbox with the function.

**Comment by gnunn1** [comment]
Do you mean a checkbox to enable/disable the history file? I don't have any plans to add shell specific options in Terminix since people tend to use a variety of shells such as zsh, bash and fish. If I'm misunderstanding feel free to elaborate.

**Comment by egmontkob** [comment]
I agree with gnunn1, configuring the shell shouldn't be the terminal emulator's job. Or if it is, why pick this single option rather than any other / all of the other hundreds?

**Comment by gitowiec** [comment]
Please tell how to configure bash in tilix to keep history?
I am using tilix as is on Ubuntu Budgie 18.04 and it is awesome, I was searching for option to keep CLI history in Tilix settings because I didn't know difference between shell and terminal (thanks to this thread now I know).
I am using default shell `(echo $0 -> /bin/bash)` - how can I turn history on?

**Comment by gitowiec** [comment]
Ok, my bad, I had .bash_history owned by root, sorry for disturbance!
