### ISSUE TITLE
"terminix --version" shows nothing when Terminix is already running

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#553]
But it works when I first close Terminix and call from e.g. gnome-terminal. As a consequence, I cannot run `terminix --version` from Terminix itself.

**Comment by gnunn1** [comment]
Just as an FYI, this is because in GTK the Application is a singleton. When you run Terminix it simply sends the request to the existing running instance and then shuts down, there is not opportunity to write to the console in the remote instance. The only way I can fix this is to process the command line before the GTK Application is instantiated. 

I've considered this in the past and deemed not worth the effort, however once you get that VTE package working this option becomes more important so I'll have a look.
