### ISSUE TITLE
Cant start terminix

### ISSUE THREAD

**Issue by dyrnade** [gnunn1/terminix#568]
Running from source, i am getting this errors.What i am missing here ?
2016-11-10T16:55:00.280:resource.d:findResource:53 Resource terminix/resources/terminix.gresource could not be found 
(terminix:12363): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Keybindings' is not installed Trace/breakpoint trap

**Comment by gnunn1** [comment]
If you are installing it from the archive in releases you need to compile the resources file:

```
unzip terminix.zip -d /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by dyrnade** [comment]
If you dont look at nix things, this is what i did to run it
https://gist.github.com/dyrnade/70702f188603c668933d698cca6c6869#file-terminix-nix-L36-L59

**Comment by gnunn1** [comment]
Unfortunately I have no idea what a nix file is, is it some sort of package file?

However looking at the output things are not ending up in the directories where terminix is expecting to find things in a traditional linux setup. This could be because of a bug on my end where I'm not using the right API for sourcing files but looking at my code everything seems in order.

On my Arch system, the terminix resource file is located at ```/usr/share/terminix/resources/terminix.gresource```. The schema file, which is what is stopping it from running, is located in ```/usr/share/glib-2.0/schemas/``` along with all the other schema files.

Can you do an ```ls``` on ```/usr/share/glib-2.0/schemas/``` and post the output here.

**Comment by dyrnade** [comment]
Yeap, Nix is a package manager. I was packaging Terminix for it and it builds without an issue but crushes at run.

There is no /usr/share in nix globally. You are kinda hacking it and all system structures are in the packages own folder itself.So, now i thought i am using compiled version so the path of glib is hardcoded in there ? i am maybe wrong, i dont know how things work under the hood of gnome.

Sorry for delayed answer.

**Comment by dsboger** [comment]
I think you are setting XDG_DATA_DIRS wrong. You should set it to `$out/share/`. The subdir `glib-2.0/schemas` is added by GSettings, according to [1]. It's worth a try, anyway.

[1] https://developer.gnome.org/gio/stable/glib-compile-schemas.html

**Comment by dsboger** [comment]
You could also have a look at this: http://stackoverflow.com/questions/35784566/meld-glib-gio-error-no-gsettings-schemas-are-installed-on-the-system

**Comment by dyrnade** [comment]
@dsboger thank you. Your suggestion `$out/share/` worked.
@gnunn1 thank you too.

**Comment by gnunn1** [comment]
Closing issue, thanks @dsboger for the help.
