### ISSUE TITLE
Rename terminal session on remote ssh

### ISSUE THREAD

**Issue by luigimolinaro** [gnunn1/terminix#577]
It is possibile to rename automatically when I connect in ssh on a remote host ?
Thank you

**Comment by f2404** [comment]
I'm using the following function as part of `~/.bashrc` file; it's changing the title for all vte-based terminals, including terminix.
```
# set terminal title to "ssh $host"
ssh()
{
  SSHAPP=`which ssh`
  ARGS=$@
  echo -en "\033]0;ssh $ARGS\007"
  $SSHAPP $ARGS
}
```

**Comment by gnunn1** [comment]
I'm in an airport so I'm answering with some brevity, I'll post a longer response tomorrow.

The easiest way to do this other then what @f2404 posted, is to use a trigger along with automatic profile switching. Unfortunately trigger support requires a patched VTE to work and only Arch has an available package for it, otherwise you would have to build VTE manually including the Terminix patches.

See the wiki for more info on automatic profile switching and triggers.

Otherwise you would have to source a script on the remote system that Terminix includes in its package for this purpose but it doesn't scale if you are dealing with 100s of servers like triggers do.

**Comment by gnunn1** [comment]
So a more in-depth comment, one of the nicest features of triggers in Terminix is to use them to match content in the terminal output and update the terminal state (hostname, username or directory). You can this user state to drive the Automatic Profile Switching feature in terminix to switch profiles when one of these states have changed.

So let's look at a concrete example. On my system, I have terminix setup to automatically make the terminal colored red when I change to the root user. To do this, I first setup my trigger as per the screenshot below:

![screenshot from 2016-11-19 11-48-05](https://cloud.githubusercontent.com/assets/9358238/20456918/5cabea3c-ae4e-11e6-96c7-9cedfd94b6d9.png)

The first trigger parses out a standard Linux command prompt (i.e. username@hostname:directory format) and updates the hostname and username state that Terminix is tracking. The second trigger does the same thing, but it parses out athe username from my powerline command line since I use powerline on my local system.

I have two profiles created, one called Default and the other called Root. The Root profile is what I use when I switch to the root user, it uses a tweaked color scheme so that it sets the background color to red.

Once I have those triggers setup, I can then use Automatic Profile switching to switch to the Root profile when I become the root user.  The screenshot below shows the configuration I am using in the Root profile to activate it:

![screenshot from 2016-11-19 11-57-06](https://cloud.githubusercontent.com/assets/9358238/20457006/4d7f45da-ae4f-11e6-982a-996d6a3482f3.png)

You can do something very similar, except select the profile based on hostname:

```
@somehostname
```

I hope this helps and answers the question. Note the trigger feature depends on havinga VTE that has been patched with terminix patches, otherwise you will not see the button to edit triggers. In Arch, this package is available in AUR [vte3-terminix-git](https://aur.archlinux.org/packages/vte3-terminix-git). For other distributions, you would need to compile it manually.
