### ISSUE TITLE
Ctrl-Scroll to zoom terminal

### ISSUE THREAD

**Issue by tobru** [gnunn1/terminix#580]
Is it possible to zoom the terminal using Ctrl-Scroll like f.e. in Terminator and many browsers? Would be great as I use this very often.

**Comment by gnunn1** [comment]
Not right now but sounds like a good idea to me, I'll have a look at adding it.

**Comment by egmontkob** [comment]
Hahaha, see https://bugs.launchpad.net/terminator/+bug/1638607 :D

(Of course it's okay if it's configurable.)

**Comment by gnunn1** [comment]
@egmontkob Wouldn't the easy solution to that one be too simply do it if ONLY the control key is pressed and no other modifiers (alt or shift)?

**Comment by egmontkob** [comment]
Inertial (or kinetic -- are these two the same?) scrolling sucks in the sense that someone (the hardware? some piece of software? which one exactly? I have no clue) keeps emitting scroll events even about a second later that you've actually released your fingers from the touchpad.

Imagine this: You scroll (because that's what you want to do, you want to scroll the history) using two-finger scrolling on the touchpad. Then you want to terminate the app (Ctrl+C) or copy-paste (Ctrl+Shift+C -- the two modifiers pressed in one order or the other) or whatever else... and zooming unexpectedly kicks in.

**Comment by gnunn1** [comment]
I've added this as an option which is off by default, thanks for the tips @egmontkob.

**Comment by leoheck** [comment]
Why disabled by default? Anyway, thanks for adding this feature.

**Comment by Flimm** [comment]
To find the relevant option, open "Preferences". It is under the "Global" section. The checkbox is labelled: "Zoom the terminal using <Control> and scroll wheel".

These keyboard shortcuts also work:
- <kbd>ctrl</kbd>-<kbd>+</kbd> Zoom in
- <kbd>ctrl</kbd>-<kbd>-</kbd> Zoom out
- <kbd>ctrl</kbd>-<kbd>0</kbd> Reset zoom

**Comment by leoheck** [comment]
The relevant thing would be enable it by default dude and not having a settings for such a small and useful feature.

**Comment by ANDROID1010** [comment]
i have problem in terminal ctrl + scroll while is not working for zoom
