### ISSUE TITLE
Option to open additional terminals in current directory

### ISSUE THREAD

**Issue by strycore** [gnunn1/terminix#598]
I've recently switched from Terminator to Terminix and so far I love it! 
However I'm missing one feature from Terminator that I find very handy: when new terminals are created the directory is kept from the Terminal it was spawn. 
For example if I'm in ~/Projects/myproject and open a new split terminal, the newly created terminal will also start in ~/Projects/myproject.

Would you consider implementing such an option in Terminix? Would you prefer a Pull Request? (I've never used D but it seems to be a neat language)

**Comment by gnunn1** [comment]
Terminix does this as well but relies on the VTE to report the current directory. Some distributions don't configure the VTE correctly to do this but fortunately it is easily fixed. You should have gotten a dialog warning you about this when you started Terminix but if not have a look at this page that provides background on the issue and how to fix it.

https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue

If the advice on that page fixes things, please close the issue otherwise let me know it's still not working and I'll help you correct it.

**Comment by strycore** [comment]
Thanks a lot, following the instructions solved the problem!
