### ISSUE TITLE
Fullscreen in quake mode

### ISSUE THREAD

**Issue by hunter-87** [gnunn1/terminix#600]
Fullscreen shortcut (F11) works fine in any normal terminix window but it seems that it does not work while in quake mode. 

Thanks for your work, this project is awesome!

**Comment by gnunn1** [comment]
I'll have a look, I vaguely remember disabling it because of an issue but the details escape me.

**Comment by DillonHeins** [comment]
It appears as though the fullscreen shortcut (F11) no longer works in quake mode. I don't know if it is just me who is experiencing this though? Any help would be greatly appreciated! :smile: 

My system is Ubuntu Gnome 16.10

**Comment by gnunn1** [comment]
It's working fine for me here on Arch Linux using Gnome 3.22. As mentioned above it was disabled initially but then re-enabled. Are you using 1.4.2?

**Comment by DillonHeins** [comment]
I checked now and I have version 1.3.5 which is odd because I just installed it today from here: https://launchpad.net/~webupd8team/+archive/ubuntu/terminix and it says on that page they have published version 1.4.2.

I will attempt to get the latest version to see if it fixes the problem (probably will)
