### ISSUE TITLE
Save window size when resized in quake mode

### ISSUE THREAD

**Issue by hunter-87** [gnunn1/terminix#602]
I'd like to know if you could add an option to preserve the size of the window, if it is resized by hand, between different invocations of quake mode. 

Quake mode is really usefull while debugging code and checking the terminal output. if i need a larger window i just resize on the fly but it's getting resetted on next quake invokation and it can be pretty annoying.

**Comment by gnunn1** [comment]
You shouldn't be able to manually re-size the window, are you saying you are able to? What Desktop Environment are you using?

**Comment by hunter-87** [comment]
i'm using the webupd8 build for ubuntu 16.04 on Unity

**Comment by gnunn1** [comment]
OK thanks, I've disabled the resize explicitly since it shouldn't be user resizable as it causes too many issues and edge cases. For example, resizing from the bottom is fine but what if you resize from the top? Also, Wayland is very flaky with the quake window and resizing just aggravates it.

Note that I've enabled fullscreen support in quake for the next release so you can just toggle that as an alternative. Hopefully that is sufficient for your needs.

**Comment by alexwhitman** [comment]
The fix for this broke quake mode for me in that it would start an 80x24 terminal in the top left of the monitor even though I'd set 100% width. Reverting 306253e977cb7a070cee10cd543b2a1cbbfa6857 fixes it for me.

**Comment by gnunn1** [comment]
Thanks @alexwhitman, I'll have to look into this some more. For now I've reverted that commit.

**Comment by gnunn1** [comment]
So I've tried a bunch of different things but on Ubuntu I can't get the window to not be resizable while still allowing the size to be set programatically.

I'll sleep on it but if I don't have a solution I'm going to close this as Won't Fix.

**Comment by gnunn1** [comment]
Unfortunately I've got nothing, closing.
