### ISSUE TITLE
Preferences window left over after closing app

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#607]
Launch terminix, open Preferences, close the terminal window - Preferences window is left open.

**Comment by gnunn1** [comment]
At first thought I'd say that's by design since it is an application window not a dialog and isn't tied to any application window. However, I can see that gedit and nautilus don't behave this way so I'm the odd man out when it comes to the HIG.

I'll look into this further and align it with what the behavior should be under the HIG.

**Comment by gnunn1** [comment]
So I asked how IRC and got pointed to this page where it clearly spells out preferences as a dialog. I'll make that change shortly.

https://developer.gnome.org/hig/stable/dialogs.html.en

**Comment by f2404** [comment]
Thanks!

**Comment by gnunn1** [comment]
I've checked in the changes to basically emulate the way gedit and nautilus works. This actually fixes quite a few issues. Since the dialog no longer gets the app menu when it is enabled it fixes #611. Also, under Ubuntu it no longer adds all of the window controls (close, maximize, minimize) so it removes the need for the side headbar to be expandable.
