### ISSUE TITLE
Gtk-CRITICAL when setting title style after changing gtk theme

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#622]
```
(terminix:25592): Gtk-CRITICAL **: gtk_tree_model_get_column_type: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed

(terminix:25592): Gtk-CRITICAL **: gtk_combo_box_set_active_id: assertion 'gtk_tree_model_get_column_type (model, column) == G_TYPE_STRING' failed

```
on selecting any option from the list. Changed gtk theme while terminix running.

**Comment by f2404** [comment]
Also happens to other lists (e.g. cursor shape); to reproduce, run terminix, then change theme, then open terminix preferences and change a value.

**Comment by gnunn1** [comment]
This doesn't seem related to theme changes directly, showing the preference dialog twice and then changing one of the combobox options triggers this error. I'm continuing to investigate, my initial suspicion does not seem to be causing the issue.

**Comment by gnunn1** [comment]
Thanks so much for reporting this, there were a couple of issues here. The first is that the preference window was not being GC'ed by D and the Settings object wasn't explicitly destroyed so it would still respond to session events. You can see this because the number of Critical Errors you get is equal to the number of times you've opened the preference dialog.

Once that was fixed, the issue was still present because D's GC is non-deterministic. So if you brought the dialog up twice and a row there was a good chance the previous instance had not been GC'ed and was still lingering in memory. I've modified the code to use the same BindingHelper class the ProfileEditor uses, this allows me to explicitly track the bindings and unbind when it is destroyed.
