### ISSUE TITLE
Synchronised scrolling/input issue

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#628]
Just noticed an issues with synchronised scrolling.  To reproduce:

1. Open a new session, split vertically, enable synchronised input
2. Generate some lines (I used `for i in {0..1000}; do echo $i; done`)
3. Hit `Ctrl+Page Up` a couple of times
4. Press enter

Expected:
Both terminals jump to the bottom, to the new prompt

Actual:
Only the active terminal jumps, the other stays in the same position.

Similar thing can be seen by hitting `Ctrl+l` to clear the terminal at stage 4.

**Comment by gnunn1** [comment]
Thanks, I'll have a look. The solution might be to have exclude specific keystrokes from the commit event and rather  pass them as key events.

**Comment by gnunn1** [comment]
The issue here is not related specifically to the enter key, but rather the option to scroll on keystroke set in the profile. Pressing any keystroke causes the same behavior when this option is enabled.

I'll need to think some about this, an obvious solution would be to scroll the other terminals programatically but the issue is that in the commit event I have no idea what caused the event to be generated, for example a paste or a keystroke. Pasting does not cause the scroll back to occur.

**Comment by gnunn1** [comment]
So in terms of how tell whether a commit is a keystroke or a paste, I decided to simply make it so that pasting also respects the "Scroll on keystroke" as well which I think meets the intent of the option. This makes it dirt simple to fix this issue and I doubt anyone will complain about this change.
