### ISSUE TITLE
Double clicking the headerbar text doesn't maximize the window

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#630]
There is a new feature in Terminix where if you single click the title you can edit it. However, double clicking should bypass this and maximize the window as expected.

**Comment by dsboger** [comment]
I don't think that is a big issue, since the same is true for every widget inside the header bar.

**Comment by phw** [comment]
I worked a bit with this, and I actually would like to have the double click work for maximizing on the title. Renaming the terminal with a single click is a absolutely brilliant feature, but I am so used to be able to double click on the header that I often enter edit mode now instead of maximizing

> I don't think that is a big issue, since the same is true for every widget inside the header bar.

Yes, but other widgets are easily recognizable as intractable UI elements, and in order to avoid triggering those in other applications I am used to click somehwere in the middle, which for Terminix is now just the wrong place to click :)

**Comment by gnunn1** [comment]
This is a bit tricky, looking at the source code for epiphany it uses a timeout set to the double-click time to tell the difference between a single and double click. Working on it...

**Comment by gnunn1** [comment]
I've checked in a fix for this, clicking the title defers showing the editor until the double click time has elapsed, if a double click occurs the timer is cancelled. I also refactored the custom title into it's own file for clarity.

**Comment by gnunn1** [comment]
Just noticed with this change that holding the mouse button down causes the edit box to appear, need to fix that.
