### ISSUE TITLE
Size of a new window differs

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#649]
... when creating it by dragging one of the terminals outside of the original window borders.
The size depends on how the terminals were split in the first place: if they were split vertically, then the new window size will be equal to the original window size; but if the terminals were split horizontally, then the new window will be half as high.
Is this intended?

**Comment by gnunn1** [comment]
I think the expectation is that the terminal itself should stay the same size which it isn't doing, I'll have a look at it.

**Comment by gnunn1** [comment]
If you add the terminal down, it works perfectly when detached in terms of preserving it's size. When adding to the right, there seems to be a threshold on the size below which it seems to want to expand it for some reason. If I drag a terminal with a width of 53 columns, it comes 81 but the number of rows stays the same. However, if I detach a terminal with 93 columns it stays the same size.

**Comment by gnunn1** [comment]
So I played around with it some more and I don't think this is a bug actually. The window itself has a minimum width which can be quite significant, when you split a terminal horizontally the two terminals are often smaller then this minimum width. When you detach one of these terminals, it gets larger in width because it's constrained by the minimum width of the window.

This is one when I was testing it above, I would see it work fine as long as the window was wider then a certain width. Any width wider then the minimum window width is maintained while anything smaller ends up equal to the minimum window width.

Does that make sense to you?

BTW an option here to help mitigate things might be to have the title support ellipsis, I'll have a look at that.

**Comment by f2404** [comment]
I think I would expect that the detached window either respects the default terminal size settings from profile preferences or takes the same size as the original window has. I've chosen the second option in xfce4-terminal.
Currently, the size is unpredictable and not correlated to the original window which I think is confusing.

**Comment by phw** [comment]
But as pointed out above the size of the terminal actually is preserved, except the case where the terminal is smaller than the minimum size constraints of the window. And I don't see how this could be done otherwise. Having a detached terminal always use a predefined default size, as you suggested as an alternative, sounds like a more restricting and confusing option to me.

**Comment by phw** [comment]
Reading everything again I think people are talking about different things here. What gnunn1 meant was that the new window will get a size depending on the actual size of the terminal being detached. That is also what I believe is a desirable behavior, since it will preserve also the layout of the contents of this terminal. So if you have e.g. a 2x2 terminal layout with equally sized terminals, detaching one will lead to a new window of roughly a quarter the size of the original window.

f2404 on the other hand seems to expect that the new window gets the same size as the window from which the terminal got detached, so in the example above the detached terminal would be enlarged. Did I understand this correctly?

**Comment by f2404** [comment]
Let's consider a default 80x24 geometry window for simplicity. Let's divide it into two terminals split horizontally so each of them is of 80 columns and (roughly) 11 rows.
Let's drag one of the terminals outside of the window. Now we have two windows: the 1st one restores its geometry to 80x24 while the 2nd (detached) one is 80x11.
This is where I can see the inconsistency: if, as @phw is saying, the desirable behavior is to preserve the layout, then why the 1st terminal changes its geometry? It should have remained 80x11 then.
But I think I'd prefer that both terminals become 80x24.

**Comment by gnunn1** [comment]
Let's talk about this in the context of source and target windows where the source window is where the terminal is dragged out of and the target window is the new window that is created for the detached terminal.

##### Source
Changing the size of the source window after the window is detached is problematic for a number of reasons including:

* If the source window has more then one session you don't want to resize the window since it would impact all sessions.

* The user can have all sorts of layouts where the "right" behavior in terms of resizing the window is contradictory or difficult to determine. For example, take the layout below. If the user detaches terminal 1, 2 or 3 what is the right behavior? Should the window be shrunk affecting terminal 4 or should 1 and 3 expand?

```
---------
|1|2|3|
---------
|   4   |
---------

* In GTK, generally changes in control visibility don't affect window sizes. For example, in gedit or gnome-terminal when you add more then one tab and the tab header appears the window doesn't grow in response, rather the content shrinks. Similarly, if you detach a tab and the tab headers disappear the window doesn't shrink, it's size is constant. In terminix I consider detaching a terminal to be along the same veins.

##### Target

The target window is sized, within the scope of the minimum window size, to fit the content that was detached. This conforms to the behavior that other Gnome applications follow, for example detaching a gedit or gnome-terminal tab keeps the content in it's original size. I tend to think that doing otherwise would violate user's expectations.

Now having said that, there could be an option to automatically resize a detached terminal to the profile size. Personally I'm not keen on that though, the option would go against the behavior of other similar apps and there is a cost in maintaining and supporting options. If there was a broad request from the community for this option I'd re-consider it but right now I'm not seeing it as something I want to do.

@f2404 Hopefully this explains my thinking and why things are the way they are. I appreciate the bug report, it was great doing a deep dive on this to clarify things.

@phw thanks for facilitating this discussion, very much appreciated.

**Comment by f2404** [comment]
@gnunn1 Thanks for elaboration. I definitely wouldn't want source window to change its geometry after detaching a terminal. For the target window, I think your explanation makes sense, and I think I don't have a better proposal or any means to pursue the default size option for now. So I'm closing the issue.

@phw Thanks for clarifications.
