### ISSUE TITLE
Option to hide title bar.

### ISSUE THREAD

**Issue by RealKindOne** [gnunn1/terminix#650]
Some terminals like ```terminator``` let you hide the title bar. Could that be possible in ```terminix```?

http://i.imgur.com/HK9L2o3.png That stuff.

**Comment by gnunn1** [comment]
It's been asked for previously and I've always said no. However it has come up a few days so perhaps it's worth having a discussion about it and soliciting some thoughts.

First off, note that this option is already implemented in quake mode. However, it works here because the quake mode window is a non-decorated window and the headerbar is added as a standalone widget rather then being set as the window titlebar.

To do the same for the normal window, it would also have to be a non-decorated window otherwise you would get the default titlebar appearing in place of the headerbar. When a window is non-decorated, the only way to move the window, AFAIK, is to hold down the Window key and move the window. Resizing a non-decorated window in Gnome isn't possible so that option wouldn't be available.

Finally, I'm just not seeing the use case for this feature, why would you want this option? In normal desktop environments (Gnome, Unity, etc) it just seems weird to me to have this oddball window that is completely out of place with every other window. For tiling window manages like i3 I can see this as being more useful but that isn't my target audience.

Could you elaborate a bit on your use case to help me understand why this feature is desirable?

**Comment by f2404** [comment]
xfce4-terminal has an option to show/hide window borders. Programmatically it's very easy - just a single function call (not counting the option code, of course).

**Comment by gnunn1** [comment]
@f2404 Thanks, good to know. I'm struggling with the "why" though, I don't get why someone want to do this? I'd love for someone to elaborate on the use case and what their workflow looks like with this option.

**Comment by f2404** [comment]
@gnunn1 I'll leave the elaboration part to @RealKindOne :)

Another thing here is that Terminix holds a lot of stuff in its titlebar, so you'd have to add it to other UI parts for cases when titlebar is hidden.

**Comment by gnunn1** [comment]
@f2404 I doubt I would move the UI elements, it would simply become keyboard driven which I think is fine for someone looking for this feature. I have this as an option already for quake mode where it makes sense IMHO, and that's the way it works there. I just don't see the "why" for a normal window hence why I'm looking for info on the use case.

**Comment by gnunn1** [comment]
@RealKindOne Any chance of elaborating on the use case as requested?

**Comment by RealKindOne** [comment]
I had been Windows for years, using Putty to ssh into various machines. Putty has no buttons and it looks perfect in my opinion. Windows machine finally kicked the bucket and I installed Debian.

I've tried multiple DE's over the months, gnome, kde, unity, etc... I kept going back to xfce4, due to various issues with other DE's and the way they look. 

Tried ```xfce4-terminal``` with the menu bar disabled for a few months, but switching between tabs got a bit annoying after awhile.
 
Switched to ```terminator```, I hid the title bar and it looks perfect in my opinion. Eventually ran into issues. 

Found ```terminix```, so far no issues. I've been used the side bar and read only, which the others do not have. 

If its too much work, don't worry about it.

http://i.imgur.com/DUqwYUY.png

**Comment by f2404** [comment]
> read only, which the others do not have

Side note: xfce4-terminal supports read-only mode.

**Comment by RealKindOne** [comment]
@f2404 Ah. Looks like that came out sometime while I was using terminator.

**Comment by gnunn1** [comment]
@RealKindOne Thanks, that last picture is very illustrative. So when you say you want to hide the titlebar, I was taking it as no titlebar whatsoever. Looking at  your screenshot thought, terminator still has the titlebar it's just not the CSD but the default system titlebar, is that correct?

Terminix does allow you to disable the CSD via a dconf setting however the headerbar then becomes a toolbar with no option to hide it.

Let me think about it and see what the best way to present this as an option is.

**Comment by gnunn1** [comment]
I'm thinking maybe a new option for Window Style with the following options:

Normal
Disable CSD
Disable CSD and hide toolbar
Borderless

I think that would cover all the options.

**Comment by gnunn1** [comment]
No I missed that, it's something I fixed for the quake window but forgot about it here. I may also need to look at appending the preferences option to the hamburger menu. I'll have a look sometime tomorrow.

**Comment by gnunn1** [comment]
I've checked in a fix for this, please test it out and let me know if it works for you.

**Comment by RealKindOne** [comment]
Thanks! Works perfectly.

**Comment by TiagoJMartins** [comment]
@gnunn1 As an additional use case (as requested), I work with a dual-head setup.
I develop exclusively in vim and constantly jump through the command-line / vim environment, in this case one of my monitors always has a terminal enabled. I've always used terminator due to the ease of use of using a single screen and being able to jump around tabs, splits, etc, with the minimum possible visual clutter.

I was recommended terminix, installed it, liked it and considered making the switch but the single option (or lack thereof) of not being able to turn off every and all borders turned me away from it.

You mentioned it would be a weird use case since the non-decorated window would feel out of place with the others, however, in my specific work case, the non-decorated window is on it's own monitor, while all the other windows are on the second monitor.

Just my two cents.

I'm eager to switch to terminix and will try it out again. Thanks!

**Comment by gnunn1** [comment]
@TiagoJMartins Thanks for the explanation, hopefully the new feature will meet your needs. One question though, wouldn't making the terminal fullscreen (F11) do what you want? It eiliminates the titlebar and chrome and fills the entire screen which I assume is what you want if it's the only app on that monitor.

**Comment by larsks** [comment]
From a strictly aesthetic perspective, I think in particular that "quake mode" would look nice without the title bar.

**Comment by agriffis** [comment]
@gnunn1 I'll open a new feature request if that makes more sense, but thought I'd jump in here first since there's context.

The flavor of this feature that I'd like is for the title bar to disappear when the window is maximized. It would be nice if this worked regardless of CSD or not, Wayland or X11, etc.

In GNOME, here is how a window looks maximized in Wayland:

![screenshot from 2017-04-05 15-51-42](https://cloud.githubusercontent.com/assets/50637/24756981/c639b64a-1aab-11e7-8ad9-cbc206539442.png)

I guess in that screenshot I had CSD disabled, but in any case, there's no point to the title bar here. I'd rather have it look like this:

![screenshot from 2017-04-05 15-56-06](https://cloud.githubusercontent.com/assets/50637/24757020/e54932e0-1aab-11e7-8c2d-6dda360ddbd5.png)

so right now I have these options:

1. run in borderless mode. This works in Wayland and X11, but has the unfortunate side-effect that non-maximized windows are also undecorated.

2. run with CSD disabled in X11 with the [pixel-saver extension](https://extensions.gnome.org/extension/723/pixel-saver/). This does pretty much exactly what I want, except that I have to run X instead of native Wayland.

How hard is it to toggle visibility of the CSD title bar on the fly? If you can detect when the window is maximized and just hide it then, that would be awesome.

P.S. I'm very happy to find tilix. As a heavy ssh-and-tmux user, I'm not much interested in the tiling features, but it's great to find a VTE3-based terminal emulator that's exploring new features!

**Comment by agriffis** [comment]
Btw I'm also familiar with F11 to run full screen, which undecorates the window. But that also hides the GNOME top bar and additionally mutes notifications, both of which I'd rather keep.

**Comment by gnunn1** [comment]
@agriffis Thanks for the suggestion and I can understand your interest in it, however I don't have any plans to add this feature. In my mind this is something that should be handled by the window manager or DE and not the application itself.

I also don't really see the point of running with the CSD disabled and then hiding the window titlebar, doesn't this still leave the toolbar (i.e the embedded headerbar) which isn't really any smaller then the headerbar?
