### ISSUE TITLE
UI request: keyboard shortcuts displayed in tooltips

### ISSUE THREAD

**Issue by almson** [gnunn1/terminix#675]
The reason many UX designers hide keyboard shortcuts is because they believe their target audience doesn't use them and therefore it would clutter the UI (even though tooltips are rarely on-screen). However, considering the target audience of a terminal emulator generally loves the keyboard, it would be very helpful if tooltips displayed shortcuts.

**Comment by gnunn1** [comment]
I can see the benefit but AFAIK no gnome applications do this and Terminix tries to fit into the Gnome platform way of doing things. The other issue is that it would only work for the very few elements in the header bar,  I don't believe popovers support this at all.

For better or worse, I think the intent in Gnome is for the shortcuts dialog to be the reference for this

**Comment by gnunn1** [comment]
I accidentally hit the comment button on my phone, oops.

Finally from an implementation point of view it gets a bit tricky since anything that displays actions would need to listen and react to shortcut changes to update the tooltip.

So long story short, at this time I don't think I will be implementing this. I do appreciate the suggestion though.
