### ISSUE TITLE
New tabs use the default profile instead of the selected one

### ISSUE THREAD

**Issue by baco** [gnunn1/terminix#676]
The selection of a diferent profile is not window-wide but tab-wide, which causes new tabs in a window to load with the default profile preferences instead of current window's one.

This bahaviour is rather anoying, for instance, when using a different profile for Quake mode; the window starts looking something but further tabs will look different unless manually changed.

**Comment by gnunn1** [comment]
Profiles are per terminal, when you split a terminal it inherits the profile, cwd, and other factors because it makes sense to do so. For a new session, I wasn't sure about this originally however since I'm not inheriting the CWD from the current terminal it probably makes sense to inherit the profile too to keep it consistent.
