### ISSUE TITLE
Library load failed: libcairo.so.2

### ISSUE THREAD

**Issue by proft** [gnunn1/terminix#682]
Hello!

I have ``terminix 1.4.2-2`` and ``cairo 1.14.8-1``.
When I start ``terminix`` I get 
```
object.Exception@../../.dub/packages/gtk-d-3.3.1/gtk-d/src/gtkc/Loader.d(123): Library load failed: libcairo.so.2
```

Before 1.4.0 everything works like a charm :)

My system is ``Arch Linux`` and I have tried reinstall ``terminix`` and ``cairo``.

**Comment by piotr-szpetkowski** [comment]
+1 same issue under latest arch linux

**Comment by piotr-szpetkowski** [comment]
@proft downgrading `harfbuzz` package to `1.3.4` solves the issue temporarily.

You can do that by for example using the version cached by pacman:
```
$ cd /var/cache/pacman/pkg
$ sudo pacman -U harfbuzz-1.3.4-1-x86_64.pkg.tar.xz
```

However the real issue is not caused by `terminix` or `harfbuzz`, but by `infinality-bundle` (if you are using it), so I suppose that the actual solution would be to uplift linked `harfbuzz` in there.

**Comment by proft** [comment]
@piotr-szpetkowski thanks for hint but I have moved to *xfce terminal* temporarily :)
by the way, I don't have ``infinality-bundle`` in my system so maybe the issue is between ``terminix`` and ``cairo`` ...

**Comment by proft** [comment]
``audacious`` don't start too :( it says that ``libharfbuzz.so.0: undefined symbol``
so, probably the issue is in ``harfbuzz``

**Comment by phw** [comment]
Working fine here with up-to-date Arch with harfbuzz 1.4.1. But this sounds a lot like the harfbuzz / infinality incompatibility discussed a lot in the Arch forums the last days. Are you sure you are using an unpatched freetype2 from the Arch repositories? What's your output of `pacman -Qs freetype`?

**Comment by phw** [comment]
> so I suppose that the actual solution would be to uplift linked harfbuzz in there.

If infinality is really the issue here the actual solution is to replace it with the freetype2 package.

**Comment by proft** [comment]
@phw I don't use ``infinality``.  
I use ``freetype2 2.6.5-2``. Yes, old version, I've added it to ``IgnorePkg`` but it works as I want.

**Comment by arcticicestudio** [comment]
I think this is a general problem at the moment, after upgrading my system at my job today (3 week vacation) and a restart the whole system seems to be broken:
  - GNOME Shelll transparent and flickering
  - no more SVG icons are rendered, so the whole icon theme is disabled
  - As soon as you try to open the "All Applications" GNOME activity overview X11 crashes, session exists with critical log and you'e back at the GDM login screen

I had to downgrade every package (178!) manually and tried to analyze which package exactly caused this massive break. There are many Reddit threads where people traced it back to the `infinality-bundle` packages too. These packages are actually out of date and the official `freetype2` package already ported its functionality in version `2.7`, so everyone should use the `freetype2` package again since it is now more updated than infinality.
Also as mentioned the broken SVG rendering is caused by the `gdk-pixbuff2` package which resulted in many new bug reports since it broke almost every GNOME system 😆 

❕  [Here](https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671) is a Gist that helps to finally replace `infinality` with `freetype2` ❕ 

Reddit threads:
  - [PSA: harfbuzz update + Infinality breaking System](https://www.reddit.com/r/archlinux/comments/5mphpu/psa_harfbuzz_update_infinality_breaking_system/)
  - [Upgrading gdk-pixbuff2 to 2.36.3-2 from 2.36.3-1 breaks SVG reading](https://www.reddit.com/r/archlinux/comments/5n16uy/upgrading_gdkpixbuff2_to_23632_from_23631_breaks/)

**Comment by phw** [comment]
> @phw I don't use infinality.
> I use freetype2 2.6.5-2. Yes, old version, I've added it to IgnorePkg but it works as I want.

No, it *worked* (past sentence) as you wanted, now it's broken ;) Since you are using Arch partial updates are unsupported. Update freetype2 and be done.

In any way, this issue should be closed. If necessary this discussion should be moved over to https://bbs.archlinux.org

**Comment by gnunn1** [comment]
Even though this isn't a terminix bug, I'll leave this up for awhile so people can see it if they run into the issue.

**Comment by proft** [comment]
Well, I've updated ``freetype2`` and ``terminix`` successfully started. 
But after that ``chromium `` has ugly hint ... this is another story :)
