### ISSUE TITLE
Add CSS class(es) to terminal title to allow customization

### ISSUE THREAD

**Issue by lburgazzoli** [gnunn1/terminix#688]
In order to quickly identify active terminals, it would be nice to have some options to customize the active terminal like:

- active/inactive title color
- active/inactive title fonts
- dim inactive panes (i.e. http://stackoverflow.com/questions/21256802/iterm2-stopping-the-inactive-pane-from-dimming)

**Comment by gnunn1** [comment]
Terminix already has an option to dim inactive panes, just use the Unfocused Dim slider under Profiles > Colors and set it to a non-zero value. You can also set the color sued for dimming in the Advanced popover in that same tab.

Otherwise the active/inactive colors and fonts are determined by the GTK theme, I do not have any plans to extend it further at this time, sorry.

**Comment by lburgazzoli** [comment]
Thx for the answer.

btw, I use Numix and for gnome-terminal the active tab has red text, but on terminix when I split the terminal I have a white or gray tile: do you ahve any specific css class to use to change it ?

**Comment by gnunn1** [comment]
There is not at the moment but I'm not adverse to adding that, let me see what I can do.

**Comment by lburgazzoli** [comment]
Maybe you can just re-use gnome-terminal settings

**Comment by gnunn1** [comment]
I have added a CSS class called ```terminix-terminal-title``` that can be used to style the title with either themes or adding some CSS to ```~/.config/gtk-3.0/gtk.css```.

**Comment by lburgazzoli** [comment]
thx

**Comment by cprog** [comment]
I use Ubuntu 16.04.5 LTS
Tilix version iinfo 

> tilix  -v
Versions
	Tilix version: 1.8.9
	VTE version: 0.42
	GTK Version: 3.18.9
Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
`

I put this in **~/.config/gtk-3.0/gtk.css**

> .terminix-terminal-title {
    background-color: #FF0000;
    padding: 0.2em;
    border: 0;
    border-color: #444;
    border-style: solid;
    border-width: 1px;
}

But I don't see any change .
What's wrong here ?

**Comment by phw** [comment]
I haven't checked , but the class is probably called tilix-terminal-title nowadays ;)

**Comment by cprog** [comment]
@phw  Thank you, it works.

**Comment by kulak** [comment]
If you want to highlight current terminal with blue and keep others with grey background, edit `~/.config/gtk-3.0/gtk.css`:

```css
.tilix-terminal-title {
	background-color: blue;
	color: 444;
	padding-left: 2;
}
.tilix-terminal-title:disabled {
	background-color: grey;
	color: black;
	padding-left: 2;
}
```

Notice use of *disabled* instead of *backdrop*.  Psedoclass *backdrop* will be used if *disabled* is not in specified and Tilix window is not in focus. However, *backdrop* will affect all shells in the window, not the focused one.

Tested on Gnome 49, Fedora 43.
