### ISSUE TITLE
Gtk-WARNING **: Allocating size to GtkScrollbar 0x2bacf90 without calling gtk_widget_get_preferred_width/height()

### ISSUE THREAD

**Issue by robclark** [gnunn1/terminix#697]
Not sure if this is a known issue.  Seems to be triggered by touchscreen scrolling (but scrolling by grabbing scrollbar is fine).  When this happens, terminix seems to hang for a few seconds.

```
Jan 17 08:07:31 thunkpad com.gexperts.Terminix[1427]: (terminix:2648): Gtk-WARNING **: Allocating size to GtkScrollbar 0x2bacf90 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

fwiw, this is on f24 (x11 session)

**Comment by f2404** [comment]
@robclark Please see https://bugzilla.gnome.org/show_bug.cgi?id=769566 - it seems to be a Gtk+ issue, and it's resolved in Gtk+ 3.22.

**Comment by robclark** [comment]
ahh, thx..  ok, I guess I probably need to stop procrastinating about upgrading to f25..

**Comment by f2404** [comment]
Yes, Fedora 25 should be free from this issue.

**Comment by pmontrasio** [comment]
I might have run into this issue on Ubuntu 16.04. Unfortunately I eventually quit Terminix are started it again and didn't run into the problem again so far (2 hours). Ubuntu 16.04 is on GTK 3.18 and it might stay there forever, so it misses the bug fix unless they'll backport to it. I can't check what happened because my ```.xsession-errors``` is empty.

This is what I experienced:

If I scroll dragging the scrollbar everything is fine. If I use the touchpad (two finger gesture) it freezes for some seconds then it jumps instantaneously to the destination. Sometimes the window gets gray like when a browser tab is stuck for a long time. I get this with scrollback 8192 or 100. I get this when scrolling back into bash and when scrolling inside ```less```.

It's the only application with this kind of problem. Gnome terminal works fine with scrollback 8192.

It seems to be related to the size of the terminal. In a full screen terminix with one wide full height terminal to the left and two narrow half height terminals to the right, only the one to the left suffers from this problem.
Dragging the separator to the left to narrow the main terminal doesn't fix the problem. The other terminal keep scrolling fine. Making terminix half height doesn't fix it either.

I'm using Terminix 1.4.2

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux connettizb 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ echo $DESKTOP_SESSION
gnome-flashback-compiz
$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64             3.18.9-1ubuntu3.1         amd64        GTK+ graphical user interface library
```

**Comment by gnunn1** [comment]
@pmontrasio I believe that's been fixed in master and is unrelated to this issue, see #669.
