### ISSUE TITLE
[Background Image] Background per profile, and not global

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#707]
Is it possible to move the background image to profile, and therefore each profile can have its own background image?

**Comment by phw** [comment]
Not sure how this would work with the tiling, as the profile is per terminal not per session.

**Comment by gnunn1** [comment]
Technically it's possible but fairly complicated since it is the window that is rendering the background and not the terminal. However I'm not in favour of adding this as a feature, to me the background image stuff is a bit gimmicky and I don't want to take on the added complexity making it per profile based. Additionally, as @phw pointed out giving the tiling nature of terminals I don't think a pastiche of terminals all with different background images is a good look.
