### ISSUE TITLE
Re-work menus in terminal titlebar

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#738]
Currently the password dialog is only available via keyboard shortcuts, and I think there is not even a default configured for it.

**Comment by gnunn1** [comment]
I think this is moving to more of a general issue as more features get added. For example, I'm working on bookmarks and it needs some menu items as well. That menu is somewhat size constrained since if you turn off the title everything goes to the context menu making it unwieldy. I'll need to look at re-organizing the menus or some other way of presenting commands.

**Comment by gnunn1** [comment]
So has discussed, now that bookmarks have been added it's a good time to re-work the terminal titlebar. Ideally the more common actions would be at the top level, the lesser used in sub-menu(s).

Based on that, here's my initial proposal for the terminal titlebar structure, suggestions welcome. If someone has a better suggestion then other I'd appreciate that as well.

```
Find
Read Only
---
Password
Bookmark
Add Bookmark
---
Profiles
---
Other
   Save Output
   Reset
   Reset and Clear
   ---
   Encoding
   Layout Options
```

   



```

**Comment by gnunn1** [comment]
I've adopted the menu structure above, probably some adjustment required once complaints start coming in.
