### ISSUE TITLE
[Bookmarks UI] More Mouse friendly

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#743]
Right now if we dont use the shortcut https://github.com/gnunn1/terminix/issues/741 we need to

1. Click on session name
2. Click on Bookmarks
3. Click on Select Bookmarks
4. Click on the Bookrmark we want from the dialog

This isn't really fast, is it? :)

One option could be to have a separated button like (Open Bookmarks) which would open the Bookmarks dialog, and that would include the add (new) bookmarks button. We dont need 2 things for that. 

Another option. Again a separated button that would bring a sidebar with bookmarks like icons, or text, or icons and text. That also need an option to select icons from each bookmarks.

To my personal use, I consistently need bookmarks, in such degree that I wouldn't mind to have a always bookmark bar visible, similar to Chrome, that I could hide/show by option.

**Comment by gnunn1** [comment]
See #738, I need to adjust the menus and bring the bookmarks to the top level. I'm not planning on adding additional buttons to the terminal titlebar, it just looks messy in my opinion. A bookmark sidebar, similar to iterm2's toolbelt, down the road might be an option but this would be a large investment in time since I'd probably adjust other aspects to use it.

With a terminal, your hands are typically on the keyboard hence the design intent I had is to use shortcuts, hence why the Select Bookmark dialog is focused on finding the bookmark via typing instead of browsing the treeview.

**Comment by alex285** [comment]
@gnunn1 Good point with shortcuts, and also I didnt get how bookmarks auto-completion works in VTE. Does it work?

About titlebar I dont find it messy. Perhaps needs a bit design changes, and then it could host some more things.
For example https://github.com/gnunn1/terminix/issues/744

**Comment by alexwhitman** [comment]
Indirectly related to this but how about exposing bookmarks via the session switching drop down (and making that more of a generic action panel)?  That way you could search for and load bookmarks via the keyboard.

**Comment by gnunn1** [comment]
@alexwhitman It's not a bad idea, unfortunately It's fairly complicated to expose the bookmarks and allow filtering since they are hierarchical. I build a custom treeview to handle this as well as other common operations for bookmarks.

I do think longer term there is merit in your suggestion in terms of having one dialog/sidebar that you can type into it and would return anything that matches be it an action, password, bookmark, session whatever.

**Comment by gnunn1** [comment]
I've adjusted the menus, closing the issue.
