### ISSUE TITLE
Use a fluid layout

### ISSUE THREAD

**Issue by mjourdan** [gnunn1/terminix#754]
I have been using terminix for a couple of weeks now, and it seems we could have a nice gnomish terminal here! Thanks! The way multiple panes are handled feels a bit counterintuitive, and could use some improvements.

Let's say I have to work on a cluster of 4 machines: I'll want to vertically divide the window in 4 equal parts. For this, I'll have to click on the split button 2 times, select the first pane, and click the split button again. I'll end up with an akward numerotation in terminal names. Let's say I want to have 3 equal terminals, now. I just can't.

My suggestion would be thinking of the buttons in the headerbar as "append" instead of "split". Splitting would still be possible by right-clicking on a specific terminal. What do you think?

**Comment by gnunn1** [comment]
You can automatically "balance" the terminals by double clicking one of the splitters, this tries to re-distribute the sizes so that all terminals come out the same horizontally though it has limitations and sometimes requires doing it twice.

The real issue is that the GTK splitter only supports two panes, thus to achieve all of the ad-hoc panes splitters gets embedded in other splitters many times. As a result, trying to do anything clean with this is very challenging.

**Comment by egmontkob** [comment]
FYI: https://bugs.launchpad.net/terminator/+bug/1521765 comment 11 onwards. (I didn't take a closer look, not sure if it made into gtk 3.22.)

**Comment by gnunn1** [comment]
Thanks @egmontkob, I'm aware of that component but it hasn't made it into GTK. I believe it is being used in Builder, I'll check if it's installed with a GIR file, might be fun to try out at some point.

**Comment by gnunn1** [comment]
I'm closing this because it is not something I am going to address at this time. Maybe if that component makes it into GTK4 I'll re-visit it, otherwise it's a limitation of GTK.

**Comment by mjourdan** [comment]
Ok, let see what happens on the gtk side. Thank you for tip by the way.
