### ISSUE TITLE
dashes appear at the top

### ISSUE THREAD

**Issue by otarassov** [gnunn1/terminix#762]
Noticed something new that occurs when enough commands have been typed to pass full page of the terminal screen. Horizontal dashes ( ------------- ) appear on top on the terminal screen.
![terminix](https://cloud.githubusercontent.com/assets/18312101/22932496/1f29b572-f296-11e6-9e69-a21ecf9bb6cf.png)

Not sure if its intended.

**Comment by gnunn1** [comment]
That's because I'm using a ScrolledWindow with overlay scrollbars in GTK 3.22, this is the normal behavior of GTK and Adwaita to indicate there is additional content.

Having said that, I think this should be disabled in a terminal. It can be done with a CSS style, I'll have a look over next weekend.

**Comment by egmontkob** [comment]
Once we used to have https://bugzilla.gnome.org/show_bug.cgi?id=757448 ... pretty much the same from a user's point of view, but could be a totally different technical story.

Just to be sure, @otarassov could you please confirm you have vte >= 0.42.3 so that you already have the aforementioned issue fixed?

**Comment by otarassov** [comment]
I have GTK ARC with  shell ARC installed but tried changing to Adwaita and still the same thing.

Here are some versions that I failed to give:

OS: fedora25

dnf list installed | grep terminix
`terminix.x86_64`                        1.4.9-0.1.fc25           @heikoada-terminix`

gtk-launch --version
`3.22.7`

echo $VTE_VERSION
`4601`


Thanks,
