### ISSUE TITLE
Dropdown menu for bookmarks

### ISSUE THREAD

**Issue by focmb** [gnunn1/terminix#788]
A dropdown menu for bookmarks would be nice.

So if I want to open a bookmark currently I have to right click, then click on bookmarks and in the new window a can choose one.

A dropdon menu in the title bar or an expansion menu in the context menu will make the work with bookmark easier.

**Comment by bil-elmoussaoui** [comment]
You can use CTRL + SHIFT +B to show the selection window directly without having to use your mouse;)

**Comment by gnunn1** [comment]
Thanks for the suggestion. I thought about doing this, the issue is that in X11 the popover cannot extend outside the window and I was worried a bookmark hierarchical menu would get too large. Additionally, like @bil-elmoussaoui suggested I really wanted this to be keyboard driven since in a terminal emulator that's whre your hands usually are.

**Comment by focmb** [comment]
Thanks,

I will try the hotkey command. I doesn't know it before and i think this will do what I want.

**Comment by ssontakke3** [comment]
> You can use CTRL + SHIFT +B to show the selection window directly without having to use your mouse;)

It worked for me !!!
