### ISSUE TITLE
Possibility to hide each terminal bar

### ISSUE THREAD

**Issue by noirbizarre** [gnunn1/terminix#79]
Hi !

Terminix is great, but the terminal bar (not the header bar) is taking a lot of space.
Is it possible to make it optional ?
Or, maybe is it possible to move the content to the header bar ?

**Comment by gnunn1** [comment]
I am planning on introducing a compact mode at some point which would move the actions to a context possible, I added conditional support for popovers as the context menu which is the first step in that direction. Note that it's not possible to move the content to the headerbar since the actions are tied to the terminal. 

This feature is a lower priority for me at the moment though.

**Comment by noirbizarre** [comment]
Glad to hear it and can't wait to use it !
Thanks for the response.

**Comment by gnunn1** [comment]
Added an option to make terminal titlebar smaller as per screenshot:
![screenshot from 2016-02-24 20-45-36](https://cloud.githubusercontent.com/assets/9358238/13309197/cdba076c-db37-11e5-8383-b6e0e8c0deac.png)

**Comment by alex285** [comment]
That isn't working on GTK 3.20. The size stays the same

**Comment by gnunn1** [comment]
Yep, that's because I'm using CSS to do it. It will need to be adjusted for 3.20 to take into account the CSS differences.
