### ISSUE TITLE
Draw bold as bright

### ISSUE THREAD

**Issue by gicmo** [gnunn1/terminix#796]
Some terminal emulator (e.g. iTerm2) have the option to "Draw bold text in bright colors" (https://iterm2.com/faq.html). I'd be nice to have that option too.

**Comment by f2404** [comment]
VTE allows setting a color for bold text; this capability is utilized in xfce4-terminal, for instance.

**Comment by gnunn1** [comment]
Hmm, I'm not sure how I missed that option in the VTE. I'll implement this shortly.

**Comment by egmontkob** [comment]
Does VTE really have such an option? :)

(There's a "bold color" but then all bold text is changed to that color, regardless of its original color. That's a stupid feature.)

**Comment by f2404** [comment]
@egmontkob Well, it's the best vte can offer here, isn't it? :)
It seems to me that, on contrary, this option affects only default-colored bold text; if bold text is already colored, it won't be touched.

**Comment by egmontkob** [comment]
@f2404 Yeah probably you're right, I don't remember the exact details :)

**Comment by f2404** [comment]
@egmontkob It doesn't seem like you're using this functionality :)

**Comment by egmontkob** [comment]
:)

**Comment by egmontkob** [comment]
Seriously: see https://bugzilla.gnome.org/show_bug.cgi?id=762247.

Bold is brightened by VTE, but (in accordance with xterm) only for the foreground, and only if it's one of the first 8 colors using the legacy escape sequences (`\e[30m` .. `\e[37m`), and not for their 256-color counterparts (`\e[38;5;0m` .. `\e[38;5;7m`).

The above URL is a feature request to be able to disable this, so that the boldness and the color attributes would finally be totally separated.

**Comment by gnunn1** [comment]
I've added the option to set the bold color, that's as much as I can do.
