### ISSUE TITLE
Add ability to select the window state on startup

### ISSUE THREAD

**Issue by jvoisin** [gnunn1/terminix#811]
Terminator has a nice option allowing its user to select the window state on startup (maximized, fullscreen, hidden, normal). It would be super-great to have the same in terminix (I'm a big fan of the "maximized on startup" thingy ♥)

**Comment by f2404** [comment]
It's already there - see terminix help.

**Comment by bil-elmoussaoui** [comment]
![screenshot from 2017-03-02 20-50-30](https://cloud.githubusercontent.com/assets/7660997/23524201/e477eaec-ff89-11e6-8f5e-e840312d4ef5.png)

**Comment by jvoisin** [comment]
Sure but it's not in the options, isn't it?

**Comment by gnunn1** [comment]
@jvoisin Thanks for the suggestion. Personally, I'm not seeing the point of having an option for it, just update your desktop file to add the command line options you want.

**Comment by jvoisin** [comment]
Ok :)

**Comment by vaijab** [comment]
Since recent versions, window state is "remembered" on startup of a new instance. I find that super annoying. I'd have a maximized window open with vim for coding, but when I open a new terminal window, I get another maximized window. That's quite odd, why would I want that? An option to disable this behaviour would be highly appreciated.
