### ISSUE TITLE
Crashes when loading multiple sessions

### ISSUE THREAD

**Issue by wagoodman** [gnunn1/terminix#813]
@gnunn1 when I try to load multiple copies of the same session terminix crashes and the terminal where I ran `terminix -s session.json -s session.json` mentions:
```
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```
Something to note about this is that there is different behavior depending on if terminix was already running or not, and how it was invoked. Specifically, the above (bad) behavior only happens when:
- terminix is alreay running and you started it from unity (super key > type "terminix" > hit enter)

Running multiple sessions works just fine when:
- you invoke `terminix -s session.json -s session.json` and then `terminix -s session.json -s session.json` again from command line.
- you invoke just `terminix` from command line and then `terminix -s session.json -s session.json` from command line.

**Comment by gnunn1** [comment]
Thanks for reporting this, I can reproduce and will have a look.

**Comment by gnunn1** [comment]
I've fixed this in master, the issue was that it was testing for the existence of the filename early which doesn't work when the command line is coming from a remote instance. At a later point if the filename doesn't exist, it prepends the remote CWD to the filename to try to resolve it.

You can workaround it in the current version by specifying a fully qualified file name rather then just the filename, i.e. use ```/home/username/test.json``` instead of ```test.json```.

**Comment by wagoodman** [comment]
Subtle... Thanks for the work around (and the quick turn around)!
