### ISSUE TITLE
Pick some "ideas" from the new iTerm2 3 Beta

### ISSUE THREAD

**Issue by edubxb** [gnunn1/terminix#86]
Iterm2 just released a [beta version](https://www.iterm2.com/version3.html) with some cool features, I think that terminix can borrow some of it to be more great.

I personally like:

* Automatic Profile Switching
* Badges
* Password Manager
* Captured Output

**Comment by gnunn1** [comment]
Note a lot of these depend on custom escape sequences and unfortunately I'm pretty limited in this regard as to what I can do due to the fact I'm using the existing VTE widget for terminal emulation instead of writing my own. I'm going to leave this open though until I have more time to investigate.

**Comment by alex285** [comment]
Password manager has been added to P-Terminal too. 
https://github.com/papyros/terminal-app/commit/3f7007d36ad7f03d5c8c5427cdd35615567df1dc

**Comment by gnunn1** [comment]
Automatic Profile Switching and Triggers are implemented, Badges and Password Manager have separate issues for them. Capturing output is done via the Save menu item, no plans to take it any further.

As a result, I'm closing this issue.

**Comment by edubxb** [comment]
Great thanks!
